translate documentation for instance method lifecycle
vuejs-id/docs pull request #120
Opened 2019-04-21 14:14 UTC by vendywira

2019-04-21 14:44 UTC, mandaputtra commented on src/v2/api/index.md
> +  Menunda eksekusi dari *callback* setelah siklus pembaharuan DOM berikutnya. Gunakan method ini sesegera mungkin setelah anda melakukan perubahan data untuk menunggu pembaharuan *DOM*. Ini sama haln
konteks

2019-04-21 14:49 UTC, mandaputtra requested changes
LGTM

2019-04-21 14:55 UTC, vendywira commented on src/v2/api/index.md
> +  Menunda eksekusi dari *callback* setelah siklus pembaharuan DOM berikutnya. Gunakan method ini sesegera mungkin setelah anda melakukan perubahan data untuk menunggu pembaharuan *DOM*. Ini sama haln
done

2019-04-21 15:05 UTC, mandaputtra approved these changes

2019-04-22 04:41 UTC, mandaputtra commented
Okay thanks mas atas kontribusinya! 😃 💯

2019-04-22 04:41 UTC, merged