Draft Opsi / Kait Siklus hidup
vuejs-id/docs pull request #121
Opened 2019-04-23 03:54 UTC by gustialfian

@mazipan @nusendra tolong direview

#106

2019-04-23 05:02 UTC, nusendra requested changes
- Masih ada beberapa yang typo
- Ada beberapa part yang perlu di terjemahkan

Selain itu udah oke, naturalisasi juga sudah oke. Thanks

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +<p class="tip">Semua kait siklus hidup secara otomatis terikat konteks `this` dengan <i>instance</i>, sehingga Anda dapat mengakses data, computed properties, dan methods. Ini berarti __Anda seharusn
```suggestion
<p class="tip">Semua kait siklus hidup secara otomatis terikat konteks `this` dengan *instance*, sehingga Anda bisa mengakses data, *computed properties*, dan *methods*. Ini berarti __Anda seharusnya tidak menggunakan *arrow function* saat mendefinisikan metode siklus hidup__ (e.g. `created: () => this.fetchTodos()`). Alasannya adalah *arrow function* mengikat konteks induk, jadi `this` tidak akan menjadi *instance* Vue seperti yang Anda harapkan dan `this.fetchTodos` akan undefined.</p>
```
italic pakai * saja, jangan pakai <i>

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>    - **See also:** [Render Functions](../guide/render-function.html)
Ini juga perlu di terjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Type:** `Function`
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Rincian

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  Dipanggil *synchronously* segera setelah *instance* telah diinisialisasi, sebelum pengaturan data observation dan event/watcher.
```suggestion
  Dipanggil secara sinkron segera setelah *instance* diinisialisasi, sebelum pengaturan data observasi dan *event/watcher*.
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **See also:** [Lifecycle Diagram](../guide/instance.html#Lifecycle-Diagram)
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  Dipanggil *synchronously* setelah *instance* dibuat. Pada tahap ini, *instance* telah selesai memproses opsi yang berarti yang berikut telah diatur: *data observation*, *computed properties*, *meth
```suggestion
  Dipanggil secara sinkron setelah *instance* dibuat. Pada tahap ini, *instance* telah selesai memproses opsi yang telah diatur: data observasi, *computed properties*, *methods*, *watch/event callbacks*. Namun, tahap pemasangan belum dimulai, dan properti `$el` belum tersedia.
```
naturalisasi

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **See also:** [Lifecycle Diagram](../guide/instance.html#Lifecycle-Diagram)
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  Dipanggin tepat sebelum pemasangan dimulai: fungsi `render` akan dipanggil untuk pertama kalinya
```suggestion
  Dipanggil tepat sebelum pemasangan dimulai: fungsi `render` akan dipanggil untuk pertama kalinya
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  **Kait ini tidak dipanggil selama rendering sisi server.**
```suggestion
  **Kait ini tidak dipanggil selama *rendering* di sisi server.**
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **See also:** [Lifecycle Diagram](../guide/instance.html#Lifecycle-Diagram)
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  Dipanggil setelah instance telah terpasang, dimana `el` digantikan oleh `vm.$el` yang baru dibuat. Jika root instance sudah terpasang ke sebuah elemen pada dokumen, `vm.$el` juga akan di dokumen ke
```suggestion
  Dipanggil setelah *instance* telah terpasang, dimana `el` digantikan oleh `vm.$el` yang baru dibuat. Jika root *instance* sudah terpasang ke sebuah elemen pada dokumen, `vm.$el` juga akan di dokumen ketika `mounted` dipanggil.
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  Perhatikan bahwa `mounted` tidak menjamin bahawa semua komponen turunannya telah terpasang. Jika Anda ingin menunggu hingga seluruh tampilan telah di-*rander*,  anda dapat menggunakan [vm.$nextTick
```suggestion
  Perhatikan bahwa `mounted` tidak menjamin bahwa semua komponen turunannya telah terpasang. Jika Anda ingin menunggu hingga seluruh tampilan telah di-*render*,  Anda bisa menggunakan [vm.$nextTick](#vm-nextTick) di dalam `mounted`
```
typo

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  **Kait ini tidak dipanggil selama rendering sisi server.**
```suggestion
  **Kait ini tidak dipanggil selama *rendering* di sisi server.**
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **See also:** [Lifecycle Diagram](../guide/instance.html#Lifecycle-Diagram)
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  Dipanggil ketika data berubahm sebelum DOM di-*patched*. Ini adalah tempat yang baik untuk mengakses DOM yang ada sebelum pembaruan, misalnya untuk menghapus *event listeners* yang ditambahkan seca
```suggestion
  Dipanggil ketika data berubah sebelum DOM di-*patched*. Ini adalah tempat yang baik untuk mengakses DOM yang ada sebelum pembaruan, misalnya untuk menghapus *event listeners* yang ditambahkan secara manual.
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  **Kait ini tidak dipanggil selama rendering sisi server, karena hanya render awal yang dilakukan di sisi server.**
```suggestion
  **Kait ini tidak dipanggil selama *rendering* di sisi server, karena hanya *render* awal yang dilakukan di sisi server.**
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **See also:** [Lifecycle Diagram](../guide/instance.html#Lifecycle-Diagram)
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  Perhatikan bahwa `updated` tidak menjamin bahawa semua komponen turunannya telah terpasang. Jika Anda ingin menunggu hingga seluruh tampilan telah di-*rander*,  anda dapat menggunakan [vm.$nextTick
```suggestion
  Perhatikan bahwa `updated` tidak menjamin bahawa semua komponen turunannya telah terpasang. Jika Anda ingin menunggu hingga seluruh tampilan telah di-*render*,  anda dapat menggunakan [vm.$nextTick](#vm-nextTick) di dalam `mounted`
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **See also:** [Lifecycle Diagram](../guide/instance.html#Lifecycle-Diagram)
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  **Kait ini tidak dipanggil selama rendering sisi server.**
```suggestion
  **Kait ini tidak dipanggil selama *rendering* di sisi server.**
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **See also:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  **Kait ini tidak dipanggil selama rendering sisi server.**
```suggestion
  **Kait ini tidak dipanggil selama *rendering* di sisi server.**
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **See also:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  **Kait ini tidak dipanggil selama rendering sisi server.**
```suggestion
  **Kait ini tidak dipanggil selama *rendering* di sisi server.**
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **See also:** [Lifecycle Diagram](../guide/instance.html#Lifecycle-Diagram)
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  Dipanggil setelah *instance* Vue dihancurkan. Ketika kait ini dipanggil, semua *directives* dari instance Vue *unbound*, semua *event listeners* telah dihapus, dan semua turunan *instance* Vue juga
```suggestion
  Dipanggil setelah *instance* Vue dihancurkan. Ketika kait ini dipanggil, semua *directives* dari *instance* Vue *unbound*, semua *event listeners* telah dihapus, dan semua turunan *instance* Vue juga telah dihancurkan.
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  **Kait ini tidak dipanggil selama rendering sisi server.**
```suggestion
  **Kait ini tidak dipanggil selama *rendering* di sisi server.**
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **See also:** [Lifecycle Diagram](../guide/instance.html#Lifecycle-Diagram)
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Type:** `(err: Error, vm: Component, info: string) => ?boolean`
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
>  - **Details:**
Ini perlu diterjemahkan

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  Dipanggil ketika galat dari komponen turunan ditangkap. Kait menerima tiga argumen: Galatnya, *instance* komponen yang memicu galat, dan string yang memmuat informasi dimana galat itu tertangkap. K
```suggestion
  Dipanggil ketika galat dari komponen turunan ditangkap. Kait menerima tiga argumen: Galatnya, *instance* komponen yang memicu galat, dan *string* yang memuat informasi dimana galat itu tertangkap. Kait dapat mengembalikan `false` untuk menghentikan galat agar tidak menyebar lebih lanjut.
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  <p class="tip">Anda dapat mengubah state komponen dalam kait ini. Namun, penting untuk memiliki persyaratan dalam template Anda atau fungsi render yang memiliki sirkuit pendek konten lain ketika ga
```suggestion
  <p class="tip">Anda dapat mengubah state komponen dalam kait ini. Namun, penting untuk memiliki persyaratan dalam templat Anda atau fungsi *render* yang memiliki sirkuit pendek konten lain ketika galat telah ditangkap; jika tidak, komponen akan dilemparkan ke *loop render* yang tak terbatas.</p>
```

2019-04-23 05:02 UTC, nusendra commented on src/v2/api/index.md
> +  - Secara default, semua kesalahan masih dikirim ke `config.errorHandler` global jika sudah didefinisikan, sehingga galat ini masih dapat dilaporkan ke layanan analitik di satu tempat.
```suggestion
  - Secara *default*, semua kesalahan masih dikirim ke `config.errorHandler` global jika sudah didefinisikan, sehingga galat ini masih dapat dilaporkan ke layanan analitik di satu tempat.
```

2019-04-23 05:36 UTC, mazipan commented on src/v2/api/index.md
>    - **See also:** [Render Functions](../guide/render-function.html)
Ini masuk bagian sebelumnya sih om @nusendra, tapi kalau mau dikerjain ya boleh banget lah

2019-04-23 06:44 UTC, nusendra commented on src/v2/api/index.md
>    - **See also:** [Render Functions](../guide/render-function.html)
oh gitu ya. oke mas

2019-04-25 06:26 UTC, gustialfian commented
@nusendra ok thanks mas, nanti saya coba revisi. mungkin agak lama ngerjainnya soalnya lagi ada kesibukan.

2019-04-25 08:50 UTC, nusendra commented
oke mas @gustialfian santai saja. :-)

2019-05-07 07:37 UTC, gustialfian commented
@nusendra sudah saya revisi mas bisa di review lagi.

2019-05-07 08:02 UTC, mazipan commented
Conflict mas @gustialfian

2019-05-07 08:05 UTC, merged