[API] Special attributes
vuejs-id/docs pull request #122
Opened 2019-04-27 16:36 UTC by HikvIneH

@mazipan @nusendra

2019-04-28 00:09 UTC, mazipan requested changes

2019-04-28 00:09 UTC, mazipan commented on src/v2/api/index.md
> +  Attribut spesial `key` kegunaan utamanya adalah sebagai petunjuk bagi *virtual DOM algorithm* dari Vue untuk mengidentifikasi *VNodes* ketika membandingkan list yang baru terhadap list yang lama. T
Kegunaan atribut spesial `key` ->
Lihat juga kata atribut pakai satu t

2019-04-28 00:09 UTC, mazipan commented on src/v2/api/index.md
> +## Attribut Spesial
Atribut

2019-04-28 00:09 UTC, mazipan commented on src/v2/api/index.md
> +  Attribut spesial `key` kegunaan utamanya adalah sebagai petunjuk bagi *virtual DOM algorithm* dari Vue untuk mengidentifikasi *VNodes* ketika membandingkan list yang baru terhadap list yang lama. T
algoritma DOM virtual

2019-04-28 00:11 UTC, mazipan requested changes

2019-04-28 00:11 UTC, mazipan commented on src/v2/api/index.md
> +  Children dari parent yang sama harus mempunyai ***unique keys***. *Keys* yang kembar/duplikat akan menyebabkan *render errors*.
Anak dari induk yang sama harus mempunyai **key yang unik**. *Key* yang sama akan mengakibatkan galat pada saat *render*

2019-04-28 00:15 UTC, mazipan requested changes

2019-04-28 00:15 UTC, mazipan commented on src/v2/api/index.md
> +  Use case yang sangat umum adalah menggabungkan *key* dengan `v-for`:
Contoh penggunaan yang paling umum adalah menggabungkan dengan `v-for`

2019-04-28 00:15 UTC, mazipan commented on src/v2/api/index.md
> +  - Memicu (Trigger) *lifecycle hooks* dari sebuah komponen dengan tepat
kata Trigger tidak perlu pakai capital awal katanya, pakai italic font.

2019-04-28 00:19 UTC, mazipan requested changes

2019-04-28 00:19 UTC, mazipan commented on src/v2/api/index.md
> +  Ketika `text` berubah, `<span>` akan selalu diganti alih-alih di *patch*, demikian sebuah transisi akan  dipicu.
kemudian -> jadi

2019-04-28 00:19 UTC, mazipan commented on src/v2/api/index.md
> +  `ref` digunakan untuk mendaftarkan referensi terhadap elemen atau *child component*. Referensi akan didaftarkan dibawah obyek `$refs` dari komponen parent. Jika digunakan pada elemen DOM polos, ref
*child component* -> komponen anak

2019-04-28 00:19 UTC, mazipan commented on src/v2/api/index.md
> +  <!-- vm.$refs.child akan menjadi komponen instance -->
akan menjadi *instance* komponen anak

2019-04-28 04:14 UTC, mandaputtra requested changes
Selain ini LGTM mas

2019-04-28 04:14 UTC, mandaputtra commented on src/v2/api/index.md
> +  Catatan pending dalam pendaftaran *ref* adalah pemilihan waktu: karena *refs* sendiri terbuat atas hasil dari *render function*, anda tidak dapat mengakses pada saat *initial render* - *refs* belum
typo: penting

2019-04-30 12:55 UTC, HikvIneH commented on src/v2/api/index.md
> +  Ketika `text` berubah, `<span>` akan selalu diganti alih-alih di *patch*, demikian sebuah transisi akan  dipicu.
Kemudian disini maksudnya "demikian" ya mas?

2019-04-30 13:06 UTC, HikvIneH commented on src/v2/api/index.md
> +  - Memicu (Trigger) *lifecycle hooks* dari sebuah komponen dengan tepat
"Memicu (*trigger*) transisi" Seperti ini ya mas?

2019-04-30 13:07 UTC, HikvIneH commented on src/v2/api/index.md
> +  Children dari parent yang sama harus mempunyai ***unique keys***. *Keys* yang kembar/duplikat akan menyebabkan *render errors*.
Key disini aku tambah pake italic font atau tidak ya?

2019-04-30 17:44 UTC, HikvIneH commented on src/v2/api/index.md
> +  Ketika `text` berubah, `<span>` akan selalu diganti alih-alih di *patch*, demikian sebuah transisi akan  dipicu.
"...jadi sebuah transisi akan terpicu."

2019-04-30 23:05 UTC, mazipan approved these changes

2019-04-30 23:05 UTC, merged