Migrating VueJS - Custom Directives
vuejs-id/docs pull request #127
Opened 2019-06-11 05:48 UTC by wendyadi

Segment Custom Directives 

Related to issue #38

2019-06-14 12:36 UTC, nusendra requested changes
dikit lagi mas. Thanks

2019-06-14 12:36 UTC, nusendra commented on src/v2/guide/migration.md
> +## Direktif Kustom <sup>disederhanakan</sup>
```suggestion
## Direktif Kustom <sup>yang disederhanakan</sup>
```

2019-06-14 12:36 UTC, nusendra commented on src/v2/guide/migration.md
> +- Direkftif tidak lagi memiliki _instance_. Maksudnya tidak lagi meiliki `this` dalam _directive hooks_. Sebaliknya, mereka menerima semua yang mereka mungkin buthkan sebagai argumen-argumen. Jika an
```suggestion
- Direkftif tidak lagi memiliki _instance_. Maksudnya tidak lagi meiliki `this` dalam _directive hooks_. Sebaliknya, mereka menerima semua yang mungkin dibutuhkan sebagai argumen-argumen. Jika anda benar-benar harus mempertahankan dalam _state_ lintas _hooks_, Anda dapat menggunakan `el`.
```

2019-06-15 14:22 UTC, mandaputtra commented
LGTM

2019-06-17 06:38 UTC, mirzacoding2 commented on src/v2/guide/migration.md
> +- Direkftif tidak lagi memiliki _instance_. Maksudnya tidak lagi meiliki `this` dalam _directive hooks_. Sebaliknya, mereka menerima semua yang mereka mungkin buthkan sebagai argumen-argumen. Jika an
sudah dibenarkan

2019-06-17 06:38 UTC, mirzacoding2 commented on src/v2/guide/migration.md
> +## Direktif Kustom <sup>disederhanakan</sup>
sudah dibenarkan

2019-06-21 07:26 UTC, merged