Cookbook/editable-svg-icons/translate to Bahasa indonesia
vuejs-id/docs pull request #160
Opened 2019-10-01 19:00 UTC by kevinmel2000

Cookbook/editable-svg-icons/translate to Bahasa indonesia

[Cookbook] - editable-svg-icons (1 FIle Translate To Bahasa Indonesia)

2019-10-01 22:05 UTC, mazipan requested changes

2019-10-01 22:05 UTC, mazipan commented on src/v2/cookbook/editable-svg-icons.md
>  ## Base Example
Contoh Dasar

2019-10-02 01:31 UTC, mazipan commented on src/v2/cookbook/editable-svg-icons.md
>  ## Base Example
cc @kevinmel2000

2019-10-02 02:44 UTC, mandaputtra requested changes

2019-10-02 02:44 UTC, mandaputtra commented on src/v2/cookbook/editable-svg-icons.md
> +## Animatable Icons(Icons Animasi)
Ikon Beranimasi (Animatable Icons)

2019-10-02 02:55 UTC, kevinmel2000 commented on src/v2/cookbook/editable-svg-icons.md
>  ## Base Example
Iya mohon maaf sudah saya commit perbaikannnya

2019-10-02 02:55 UTC, kevinmel2000 commented on src/v2/cookbook/editable-svg-icons.md
> +## Animatable Icons(Icons Animasi)
Iya mohon maaf, sudah saya commit perbaikannnya

2019-10-02 03:01 UTC, mandaputtra approved these changes

2019-10-02 03:01 UTC, mandaputtra commented
LGTM

2019-10-02 03:01 UTC, merged