Translate Bahasa Indonesia : Vue Instance
vuejs-id/docs pull request #51
Opened 2019-03-06 09:55 UTC by iqbalaqaba

Hasil translate bahasa indonesia dari **Vue Instance** 🚀

2019-03-06 10:04 UTC, mazipan requested changes

2019-03-06 10:04 UTC, mazipan commented on src/v2/guide/instance.md
> +title: Permintaan Vue
Permintaan Vue ini gak familiar kata2nya.
Mending pertahankan Vue Instance

2019-03-06 10:04 UTC, mazipan commented on src/v2/guide/instance.md
> +## Membuat Permintaan Vue
Membuat Vue Instance

2019-03-06 10:07 UTC, mazipan requested changes

2019-03-06 10:07 UTC, mazipan commented on src/v2/guide/instance.md
> +Setiap aplikasi Vue dimulai dengan membuat **Permintaan Vue** dengan fungsi `Vue` seperti berikut :
Vue instance

2019-03-06 10:07 UTC, mazipan commented on src/v2/guide/instance.md
> +Meskipun tidak dengan terkait dengan ketat dengan [Pola MVVM](https://en.wikipedia.org/wiki/Model_View_ViewModel), desain yang dimiliki Vue sebagian terinspirasi oleh konsep tersebut. Sebagai ketentu
Semua Vue Instance, jangan di terjemahkan.
Pakai italic font aja.

2019-03-06 10:12 UTC, mazipan requested changes

2019-03-06 10:12 UTC, mazipan commented on src/v2/guide/instance.md
> +Ketika anda membuat permintaan Vue, anda mengirimkan **objek pilihan**. Sebagian besar dari panduan ini menjelaskan bagaimana anda bisa menggunakan opsi ini untuk membuat tindakan yang anda inginkan.
**objek pilihan** --> **obyek opsi (options object)**

2019-03-06 10:12 UTC, mazipan commented on src/v2/guide/instance.md
> +Ketika anda membuat permintaan Vue, anda mengirimkan **objek pilihan**. Sebagian besar dari panduan ini menjelaskan bagaimana anda bisa menggunakan opsi ini untuk membuat tindakan yang anda inginkan.
anda -> Anda, pakai capital A

2019-03-06 10:12 UTC, mazipan commented on src/v2/guide/instance.md
> +Sebuah aplikasi Vue terdiri dari **permintaan dasar Vue** yang dibuat dengan `new Vue`, secara opsional di atur ke dalam struktur pohon, komponen yang bisa digunakan ulang. Sebagai contoh, komponen a
**root Vue instance** -> **akar (root) Vue instance**
tree of nested gak usah di terjemahkan, pake italic aja.
terliat -> terlihat

2019-03-06 10:13 UTC, mazipan requested changes

2019-03-06 10:13 UTC, mazipan commented on src/v2/guide/instance.md
> +Kita akan membiacarakan tentang [sistem komponen](components.html) pada detail selanjunya. Sekarang, dengan hanya mengetahui bahwa semua komponen Vue juga adalah permintaan Vue, dan jug menerima opsi
membiacarakan typo --> membicarakan
selanjunya typo --> selanjutnya
permintaan Vue -> Vue instance
jug -> juga

2019-03-06 16:28 UTC, iqbalaqaba commented
Thank you reviewnya mas @mazipan , sudah saya pr ulang yang baru 😉

2019-03-06 23:32 UTC, mazipan requested changes

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +Meskipun tidak dengan terkait dengan ketat dengan [Pola MVVM](https://en.wikipedia.org/wiki/Model_View_ViewModel), desain yang dimiliki Vue sebagian terinspirasi oleh konsep tersebut. Sebagai ketentu
Meskipun tidak terkait ketat, typo kebanyakan keulang kata

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +Ketika anda membuat *Vue Instance*, anda mengirimkan **obyek opsi**. Sebagian besar dari panduan ini menjelaskan bagaimana anda bisa menggunakan opsi ini untuk membuat tindakan yang anda inginkan. Se
Semua kata anda, ganti dengan Anda pakai A capital

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +Kita akan membicarakan tentang [sistem komponen](components.html) pada detail selanjutnya. Sekarang, dengan hanya mengetahui bahwa semua komponen Vue juga adalah *Vue Instance*, dan juga menerima ops
opsi objek -> objek opsi

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +Ketika *Vue Instance* dibuat, ini menambah semua properti yang ditemukan di dalam objek `data` ke Vue's **sistem reaktifitas**. Ketika nilai dari properti tersebut berubah, tampilanya akan "bereaksi"
ke **sistem reaktif** milik Vue

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +// Mendapat properti dari permintaan
Permintaan-> instance

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +// Mengatur properti pada permintaan
Permintaan -> instance

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +Ketika data ini berubah, tampilanya akan berubah. Itu harus dicatat bahwa properti di `data` adalah yang satu satunya **reaktif** jika mereka ada pada saat permintaan dibuat. Itu berarti kamu harus m
permintaan-> instance

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +Satu satunya pengecualian untuk ini adalah menggunakan `Object.freeze()`, yang mencegah properti untuk dirubah, yang juga berarti reaktifitas sistem yang tidak bisa _menarik_ perubahan.
dirubah-> diubah

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +Satu satunya pengecualian untuk ini adalah menggunakan `Object.freeze()`, yang mencegah properti untuk dirubah, yang juga berarti reaktifitas sistem yang tidak bisa _menarik_ perubahan.
Track, bukan menarik terjemahannya tapi melacak

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +  <!-- ini tidak akan mengubah `foo`! -->
tidak akan lagi

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +Untuk tambahan ke data properti, *Vue Instance* menunjukan sejumlah properti permintaan dan metode yang berguna. Ini juga diawalai dengan `$` untuk membedakan mereka dari properti yang ditetapkan-pen
Permintaan-> instance

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +Untuk tambahan ke data properti, *Vue Instance* menunjukan sejumlah properti permintaan dan metode yang berguna. Ini juga diawalai dengan `$` untuk membedakan mereka dari properti yang ditetapkan-pen
Ditetapkan pengguna, gak perlu dash lagi

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +// $watch adalah metode permintaan
Permintaan-> instance

2019-03-06 23:32 UTC, mazipan commented on src/v2/guide/instance.md
> +  // Panggilan balik ini akan di panggil ketika `vm.a` berubah
Panggilan balik (callback)

2019-03-07 01:57 UTC, iqbalaqaba commented on src/v2/guide/instance.md
> +Kita akan membicarakan tentang [sistem komponen](components.html) pada detail selanjutnya. Sekarang, dengan hanya mengetahui bahwa semua komponen Vue juga adalah *Vue Instance*, dan juga menerima ops
mas @mazipan , bagaimana kalau pilihan objek ?

2019-03-07 02:17 UTC, mazipan requested changes

2019-03-07 02:17 UTC, mazipan commented on src/v2/guide/instance.md
> +Meskipun tidak dengan terkait ketat dengan [Pola MVVM](https://en.wikipedia.org/wiki/Model_View_ViewModel), desain yang dimiliki Vue sebagian terinspirasi oleh konsep tersebut. Sebagai ketentuan, kit
Masih berulang kata2nya.

Harusnya -> Meskipun tidak terkait ketat dengan

2019-03-07 02:17 UTC, mazipan commented on src/v2/guide/instance.md
> +Sebuah aplikasi Vue terdiri dari **permintaan dasar Vue** yang dibuat dengan `new Vue`, secara opsional di atur ke dalam akar (root) *Vue Instance*, komponen yang bisa digunakan ulang. Sebagai contoh
Permintaan -> instance

2019-03-07 02:17 UTC, mazipan commented on src/v2/guide/instance.md
> +Ketika *Vue Instance* dibuat, ini menambah semua properti yang ditemukan di dalam objek `data` ke **sistem reaktif** milok Vue. Ketika nilai dari properti tersebut berubah, tampilanya akan "bereaksi"
Milok typo

2019-03-07 02:17 UTC, mazipan commented on src/v2/guide/instance.md
> +## Siklus Hidup Pengait Permintaan
Permintaan->Instance

2019-03-07 02:17 UTC, mazipan commented on src/v2/guide/instance.md
> +## Siklus Hidup Pengait Permintaan
Siklus Hidup Pengait (Lifecycle Hook)

2019-03-07 02:39 UTC, mazipan approved these changes

2019-03-07 02:39 UTC, iqbalaqaba commented on src/v2/guide/instance.md
> +Sebuah aplikasi Vue terdiri dari **permintaan dasar Vue** yang dibuat dengan `new Vue`, secara opsional di atur ke dalam akar (root) *Vue Instance*, komponen yang bisa digunakan ulang. Sebagai contoh
berarti saya ubah semua kata *permintaan* jadi **instance**

2019-03-07 02:40 UTC, merged

2019-03-07 02:40 UTC, iqbalaqaba commented
Thank you atas reviewnya mas @mazipan 🚀

2019-03-07 02:41 UTC, mazipan commented
Terima kasih kembali atas kontribusinya mas @iqbalaqaba