ID translation of TypeScript Support page
vuejs-id/docs pull request #52
Opened 2019-03-06 13:14 UTC by dikisiswanto

2019-03-06 13:34 UTC, mazipan requested changes
Butuh perbaikan sedikit mas

2019-03-06 13:34 UTC, mazipan commented on src/v2/guide/typescript.md
> +> [Vue CLI](https://cli.vuejs.org) menyediakan dukungan perkakas TypeScript bawaan. Pada versi mayor Vue yang akan datang (3.x), kami juga berencana untuk meningkatkan dukungan TypeScript dengan *bui
Mending tetep pakai built-in (pake dash) aja kali ya? Lebih familiar

2019-03-06 13:34 UTC, mazipan commented on src/v2/guide/typescript.md
> +  // penyimpulan tipe diaktifkan
Ini apa lebih baik kita tambahkan aslinya, jadi pengumpulan tipe (*type inference*) diaktifkan

2019-03-06 13:34 UTC, mazipan commented on src/v2/guide/typescript.md
> +  // sebab TypeScript tidak dapat memberitahu pilihan ini untuk Vue componen.
componen -> kurang t

2019-03-06 13:34 UTC, mazipan commented on src/v2/guide/typescript.md
> +  // sebab TypeScript tidak dapat memberitahu pilihan ini untuk Vue componen.
Atau bisa pakai komponen Vue

2019-03-06 13:34 UTC, mazipan commented on src/v2/guide/typescript.md
> +## Menandai Tipe Kembalian
Menganotasi ?

2019-03-06 13:41 UTC, dikisiswanto commented
Sudah diperbarui sesuai ulasan.

2019-03-06 14:05 UTC, mazipan approved these changes

2019-03-06 14:05 UTC, merged

2019-03-06 23:54 UTC, dikisiswanto reviewed
Masih ada kesalahan

2019-03-06 23:54 UTC, dikisiswanto commented on src/v2/guide/typescript.md
> +Untuk mengembangkan aplikasi Vue dengan TypeScript, kami sangat menyarankan Anda menggunakan [Visual Studio Code](https://code.visualstudio.com/), yang menyediakan dukungan luar biasa untuk TypeScrip
`And` harusnya `dan`

2019-03-07 00:57 UTC, mazipan commented
Di PR ulang mas @dikisiswanto kalau ada perbaikan atau perubahan ya.