halaman Template Syntax
vuejs-id/docs pull request #54
Opened 2019-03-06 17:23 UTC by huiralb

2019-03-06 23:39 UTC, mazipan requested changes
Udah bagus mas, butuh perubahan sedikit aja.
Abis itu dibenerin kita bisa merge ini ya mas .

2019-03-06 23:39 UTC, mazipan commented on src/v2/guide/syntax.md
> +Vue.js menggunakan sintaks templat berbasis HTML yang memungkinkan anda secara deklaratif untuk binding hasil render DOM yang mendasari data dari Vue instance. Semua templat Vue.js adalah HTML yang v
Semua kata Anda pake huruf A capital mas.

2019-03-06 23:39 UTC, mazipan commented on src/v2/guide/syntax.md
> +Pada dasarnya, Vue mengkompilasi templat ke dalam fungsi render Virtual DOM. Dikombinasikan dengan sistem reaktivitas, Vue mampu secara cerdas mencari tahu jumlah minimum komponen untuk render ulang
Virtual DOM -> DOM Virtual

2019-03-06 23:39 UTC, mazipan commented on src/v2/guide/syntax.md
> +<span v-once>Ini tidak akan berubah: {{ msg }}</span>
tidak akan peenah

2019-03-07 04:28 UTC, huiralb commented
terimakasih atas review nya mas @mazipan . Dan sudah saya revisi lagi. Silahkan bisa dicek lagi.

2019-03-07 04:33 UTC, mazipan commented
Kena conflict nih mas @huiralb, bisa dibantu buat resolved juga gak ya?

2019-03-07 11:09 UTC, huiralb commented
bisa saja sih mas @mazipan . cara resolved nya bagaimana? clone langsung ke vuejs-id/docs ?

2019-03-07 12:34 UTC, merged