Translate Bahasa Indonesia dari : Component Registration
vuejs-id/docs pull request #62
Opened 2019-03-07 09:31 UTC by iqbalaqaba

Hasil translate bahasa indonesia untuk halaman : Component Registration 🚀

2019-03-07 10:00 UTC, logustra commented on src/v2/guide/components-registration.md
> +> Halaman ini menganggap anda telah membaca [Komponen Dasar](components.html). Baca itu dahulu jika anda baru pada komponen.
halaman ini menganggap anda telah membaca => halaman ini berasumsi bahwa anda sudah membaca

2019-03-07 10:00 UTC, logustra commented on src/v2/guide/components-registration.md
> +Ketika mendaftarkan sebuah komponen, itu akan diberi sebuah nama. Sebagai contoh, didalam sebuah daftar global kita telah melihat:
Ketika mendaftarkan sebuah komponen, itu akan diberi sebuah nama => Ketika mendaftarkan komponen, itu akan selalu diberi nama

2019-03-07 10:00 UTC, logustra commented on src/v2/guide/components-registration.md
> +Ketika mendaftarkan sebuah komponen, itu akan diberi sebuah nama. Sebagai contoh, didalam sebuah daftar global kita telah melihat:
Sebagai contoh, didalam sebuah daftar global kita telah melihat: => Misalnya, dalam pendaftaran global yang telah kita lihat sejauh ini:

2019-03-07 10:00 UTC, logustra commented on src/v2/guide/components-registration.md
> +Nama sebuah komponen adalah argumen pertama dari `Vue.component`.
Nama sebuah komponen => Nama komponen

2019-03-07 10:00 UTC, logustra commented on src/v2/guide/components-registration.md
> +Ketika mendefinisikan sebuah komponen dengan *PascalCase*, anda dapat menggunakan kedua hal ketika memberi referensi ke *custom* elemenya. Itu berarti, kedua `<nama-komponen-saya>` dan `<NamaKomponen
Ketika mendefinisikan sebuah komponen => Ketika mendefinisikan komponen

2019-03-07 10:14 UTC, logustra commented
tolong sebelum membuat PR, hasil translatenya di baca lagi dari atas sampai bawah, buat mastiin aja, apakah hasil translate kita udah terlihat natural atau belum.
thanks 😄

2019-03-07 11:36 UTC, iqbalaqaba commented
> tolong sebelum membuat PR, hasil translatenya di baca lagi dari atas sampai bawah, buat mastiin aja, apakah hasil translate kita udah terlihat natural atau belum.
> thanks 😄

well, thank you checkingnya 😉 . kayanya mas @mazipan / mas @nusendra masih liburan wkkw, gonna fix this soon after admin approval.

2019-03-07 13:04 UTC, mazipan requested changes

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +> Halaman ini berasumsi anda telah membaca [Komponen Dasar](components.html). Baca itu dahulu jika anda baru pada komponen.
semua kata anda -> ganti Anda, capital A

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +> Halaman ini berasumsi anda telah membaca [Komponen Dasar](components.html). Baca itu dahulu jika anda baru pada komponen.
Baca halaman itu terlebih dahulu bila Anda belum mengerti komponen

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Ketika mendaftarkan sebuah komponen, itu akan selalu diberi nama. Misalnya, dalam sebuah daftar global yang kita lihat sejauh ini:
Ketika mendaftarkan sebuah komponen, selalu berikan nama. Misalnya, untuk sebuah registrasi global kita akan melihat seperti berikut:

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Nama yang anda berikan ke komponen mungkin tergantung pada dimana anda akan menggunakanya. Ketika menggunakan komponen secara langsung didalam DOM ( sebagai lawan didalam *template string* atau [komp
menggunakannya -> double huruf n

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Nama yang anda berikan ke komponen mungkin tergantung pada dimana anda akan menggunakanya. Ketika menggunakan komponen secara langsung didalam DOM ( sebagai lawan didalam *template string* atau [komp
didalam -> di dalam

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Nama yang anda berikan ke komponen mungkin tergantung pada dimana anda akan menggunakanya. Ketika menggunakan komponen secara langsung didalam DOM ( sebagai lawan didalam *template string* atau [komp
komponen single-file -> berkas komponen tunggal (single file component)

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Anda bisa melihat rekomendasi lainya untuk nama nama komponen di [Aturan Gaya](../style-guide/#Base-component-names-strongly-recommended).
Aturan Gaya -> Panduan Gaya

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Komponen ini **teregistrasi secara global**. Itu berarti mereka dapat digunakan didalam *template* dari semua *root Vue Instance* (`new Vue`) dibuat setelah diregistrasi. Sebagai contoh:
didalam -> di dalam

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Ini bahkan berlaku kepada semua subkomponen, berarti tiga komponen tersebut juga tersedia _didalam satu sama lain_.
sub komponen

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Registrasi global jarang menjadi ideal. Sebagai contoh, ketika anda menggunakan *build system* seperti Webpack, meregristasi global semua komponen berarti ketika anda berhenti menggunakan sebuah komp
meregristasi -> typo, meregistrasi

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Lalu tetapkan komponen komponen yang akan anda gunakan di pilihan `components`
di opsi komponen

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Untuk setiap properti didalam objek `components`, kuncinya akan menjadi nama dari elemen *custom*, ketika nilai akan berisi pilihan objek dari komponen tersebut.
Di cek lagi banyak yang nulisnya "didalam" harusnya "di dalam"

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Catat bahwa **komponen yang terdaftar secara lokal juga _tidak_ terdapat di dalam _subkomponen_**. Sebagai contoh, jika anda ingin `Component A` terdapat di dalam `Component B`, anda harus menggunaka
sub komponen

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Atau jika anda tertarik menggunakan modul ES2015, seperti melewati Babel dan Webpack, itu akan lebih terlihat seperti:
Kata tertarik dihapus aja.

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Atau jika anda tertarik menggunakan modul ES2015, seperti melewati Babel dan Webpack, itu akan lebih terlihat seperti:
seperti melewati -> seperti menggunakan

2019-03-07 13:04 UTC, mazipan commented on src/v2/guide/components-registration.md
> +Cata bahwa di ES2015+, menempatkan nama variabel seperti `ComponentA` didalam *shorthand* objek untuk`ComponentA: ComponentA`, berarti nama dari kedua variabel adalah:
Cata -> Catat

2019-03-08 02:19 UTC, iqbalaqaba commented
Updated mas @mazipan 😉

2019-03-08 04:09 UTC, mazipan approved these changes

2019-03-08 04:09 UTC, merged