Routing
vuejs-id/docs pull request #64
Opened 2019-03-07 10:09 UTC by superpikar

routing translation is done, please direview mas @nusendra @mazipan

2019-03-07 10:34 UTC, nusendra requested changes
Dikit lagi. :-)

2019-03-07 10:34 UTC, nusendra commented on src/v2/guide/routing.md
> +Dikombinasikan dengan *HTML5 History API*, Anda dapat membuat *client-side router* yang sangat mendasar namun berfungsi penuh. Untuk melihatnya dalam implementasi, cek [contoh aplikasi ini](https://g
```suggestion
Dikombinasikan dengan *HTML5 History API*, Anda dapat membuat *client-side router* yang sangat mendasar namun berfungsi penuh. Untuk melihat bagaimana cara mengimplementasikannya, silakan cek [contoh aplikasi ini](https://github.com/chrisvfritz/vue-2.0-simple-routing-example)
```
natural

2019-03-07 13:13 UTC, mazipan requested changes

2019-03-07 13:13 UTC, mazipan commented on src/v2/guide/routing.md
> +Jika Anda hanya membutuhkan *routing* yang sangat simpel dan tidak melibatkan fitur lengkap dari pustaka *router*, Anda dapat melakukannya dengan me-*render* *page-level* komponen sebagai berikut :
Anda bisa melakukannya dengan me-*render* secara dinamis sebuah komponen yang berperan sebagai halaman seperti berikut:

2019-03-07 13:13 UTC, mazipan commented on src/v2/guide/routing.md
> +## Integrasi dengan *Routers* pihak ketiga
Cukup "Router" tanpa s

2019-03-08 01:34 UTC, superpikar commented on src/v2/guide/routing.md
> +Dikombinasikan dengan *HTML5 History API*, Anda dapat membuat *client-side router* yang sangat mendasar namun berfungsi penuh. Untuk melihatnya dalam implementasi, cek [contoh aplikasi ini](https://g
done mas, terimakasih sarannya

2019-03-08 01:35 UTC, superpikar commented on src/v2/guide/routing.md
> +Jika Anda hanya membutuhkan *routing* yang sangat simpel dan tidak melibatkan fitur lengkap dari pustaka *router*, Anda dapat melakukannya dengan me-*render* *page-level* komponen sebagai berikut :
done mas, terimakasih sarannya.

2019-03-08 01:35 UTC, superpikar commented on src/v2/guide/routing.md
> +## Integrasi dengan *Routers* pihak ketiga
done mas, terimakasih sarannya.

2019-03-08 02:28 UTC, nusendra approved these changes

2019-03-08 04:01 UTC, mazipan approved these changes

2019-03-08 04:01 UTC, merged