Translation Unit Testing
vuejs-id/docs pull request #68
Opened 2019-03-07 12:40 UTC by wendyadi

Translation Halaman unit testing untuk issue #31

2019-03-07 12:42 UTC, wendyadi commented
@nusendra 
Mohon feedbacknya
Ada beberapa istilah yang saya bingung apakah baiknya di translate atau tidak?

Contohnya:
assertion, options, raw options, component, testable

2019-03-07 13:30 UTC, nusendra commented
@wendyadi untuk istilah yang kalau dijadikan indonesia malah tambah membingungkan, tetapi saja pakai versi inggris nya, cuman dibikin italic saja

untuk component diganti jadi komponen

2019-03-07 13:35 UTC, mazipan requested changes

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +> [Vue CLI](https://cli.vuejs.org/) memiliki opsi built-in untuk melakukan unit testing menggunakan [Jest](https://github.com/facebook/jest) atau [Mocha](https://mochajs.org/) yang bisa berjalan tanp
built-in -> bawaan

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +> [Vue CLI](https://cli.vuejs.org/) memiliki opsi built-in untuk melakukan unit testing menggunakan [Jest](https://github.com/facebook/jest) atau [Mocha](https://mochajs.org/) yang bisa berjalan tanp
library -> pustaka

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +> [Vue CLI](https://cli.vuejs.org/) memiliki opsi built-in untuk melakukan unit testing menggunakan [Jest](https://github.com/facebook/jest) atau [Mocha](https://mochajs.org/) yang bisa berjalan tanp
Setup kayanya lebih baik diterjemahkan jadi penyetelan atau setelan

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +## Pengujian/Assertion Sederhana
Pengujian (*Assertion*) Sederhana

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +Anda tidak perlu melakukan hal khusus untuk membuat komponen-komponen Anda testable (dapat dites). Export raw options:
bisa dites (*testable*)

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +Anda tidak perlu melakukan hal khusus untuk membuat komponen-komponen Anda testable (dapat dites). Export raw options:
Cukup ekspor opsi seperti berikut:

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +Kemudian import options komponen tersebut bersama dengan Vue, dan Anda dapat membuat banyak assertion umum (disini kita menggunakan Jasmine/Jest style `expect` assertion sebagai contoh)
Kemudian impor opsi komponen

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +Kemudian import options komponen tersebut bersama dengan Vue, dan Anda dapat membuat banyak assertion umum (disini kita menggunakan Jasmine/Jest style `expect` assertion sebagai contoh)
Kata asing kaya assertion mesti pakai italic mas

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +Kemudian import options komponen tersebut bersama dengan Vue, dan Anda dapat membuat banyak assertion umum (disini kita menggunakan Jasmine/Jest style `expect` assertion sebagai contoh)
Jasmine/Jest style -> gaya Jasmine/Jest

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +// menggunakan test runner / library assertion apa pun yang Anda sukai
Library -> Pustaka

2019-03-07 13:35 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +## Tulis Komponen yang Dapat Dites
Tulis -> Menulis

2019-03-07 13:43 UTC, nusendra requested changes
Bahasa sudah lumayan natural, cuman masih banyak istilah inggris yang belum di bikin italic.

Mohon bantuannya, terima kasih mas :-)

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +> [Vue CLI](https://cli.vuejs.org/) memiliki opsi built-in untuk melakukan unit testing menggunakan [Jest](https://github.com/facebook/jest) atau [Mocha](https://mochajs.org/) yang bisa berjalan tanp
```suggestion
> [Vue CLI](https://cli.vuejs.org/) memiliki opsi *built-in* untuk melakukan *unit testing* menggunakan [Jest](https://github.com/facebook/jest) atau [Mocha](https://mochajs.org/) yang bisa berjalan tanpa konfigurasi tambahan. Kami juga memiliki pustaka resmi [Vue Test Utils](https://vue-test-utils.vuejs.org/) yang menyediakan panduan lebih detail untuk konfigurasi kustom.
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +Anda tidak perlu melakukan hal khusus untuk membuat komponen-komponen Anda testable (dapat dites). Export raw options:
```suggestion
Anda tidak perlu melakukan hal khusus untuk membuat komponen-komponen Anda *testable* (dapat dites). Ekspor *raw options*:
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +Kemudian import options komponen tersebut bersama dengan Vue, dan Anda dapat membuat banyak assertion umum (disini kita menggunakan Jasmine/Jest style `expect` assertion sebagai contoh)
```suggestion
Kemudian impor opsi dari komponen tersebut bersama dengan Vue, dan Anda dapat membuat banyak *assertion* umum (disini kita menggunakan Jasmine/Jest dengan gaya `expect` *assertion* sebagai contoh)
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +// Import vue dan komponen yang akan dites
```suggestion
// Impor vue dan komponen yang akan dites
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +// Berikut adalah Jasmine 2.0 tests, Anda dapat
```suggestion
// Berikut adalah Jasmine 2.0 tests, Anda bisa
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +// menggunakan test runner / library assertion apa pun yang Anda sukai
```suggestion
// menggunakan *test runner* / pustaka *assertion* apa pun yang Anda sukai
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +  // Periksa raw options komponen
```suggestion
  // Periksa komponen raw options
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +  // Evaluasi hasil dari function-function di
```suggestion
  // Evaluasi hasil dari beberapa fungsi di
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +  // raw options komponen
```suggestion
  // komponen raw options
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +Hasil render dari sebuah komponen secara utama ditentukan oleh properti-properti yang diterima komponen tersebut. Jika hasil render dari sebuah komponen hanya bergantung pada properti-nya -- maka aka
```suggestion
Hasil *render* dari sebuah komponen yang paling utama ditentukan oleh properti-properti yang diterima komponen tersebut. Jika hasil *render* dari sebuah komponen hanya bergantung pada properti-nya -- maka hal tersebut akan mudah untuk di tes, mirip dengan menjalankan *assertion* pada fungsi yang memiliki bermacam-macam argumen. Berikut contoh sederhananya:
```
harus menggunakan bahasa yang natural

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +Anda dapat melakukan assertion pada hasil render dengan properti yang berbeda0-beda menggunakan opsi `propsData`:
```suggestion
Anda bisa melakukan *assertion* pada hasil *render* menggunakan properti yang berbeda-beda menggunakan opsi `propsData`:
```
bahasa natural dan typo

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +// fungsi helper / pembantu yang melakukan mounts kemudian me-return text yang di-render
```suggestion
// fungsi *helper* / pembantu yang menjalankan *mounts* kemudian mengembalikan teks yang di-render
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +Karena Vue [melakukan update pada DOM secara asynchronous](reactivity.html#Async-Update-Queue), assertion pada update DOM yang disebabkan oleh perubahan state harus dilakukan dalam callback `Vue.next
```suggestion
Karena Vue [melakukan update pada DOM secara asynchronous](reactivity.html#Async-Update-Queue), *assertion* pada *update* DOM yang disebabkan oleh perubahan *state* harus dilakukan dalam *callback* `Vue.nextTick`:
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +  // Tunggu satu tick setelah perubahan state sebelum menguji DOM yang terupdate
```suggestion
  // Tunggu satu "tick" setelah perubahan *state* sebelum menguji DOM yang terupdate
```

2019-03-07 13:43 UTC, nusendra commented on src/v2/guide/unit-testing.md
> +Untuk informasi yang lebih mendalam untuk unit testing di Vue, kunjungi [Vue Test Utils](https://vue-test-utils.vuejs.org/) dan cookboook entry kami tentang [unit testing vue components](https://vuej
```suggestion
Untuk informasi yang lebih mendalam untuk *unit testing* di Vue, kunjungi [Vue Test Utils](https://vue-test-utils.vuejs.org/) dan *cookboook* entri kami tentang [unit testing vue components](https://vuejs.org/v2/cookbook/unit-testing-vue-components.html)
```

2019-03-07 15:05 UTC, wendyadi commented
@mazipan @nusendra 
FYI: Ini di style markdownnya kalau di-italic, warna textnya jadi abu2 ya.
Ini saya italic in dlu

<img width="595" alt="screen shot 2019-03-07 at 22 04 04" src="https://user-images.githubusercontent.com/13862336/53966067-0087b580-4125-11e9-9ead-fe7e76fdc28e.png">

2019-03-07 15:09 UTC, wendyadi commented on src/v2/guide/unit-testing.md
> +// menggunakan test runner / library assertion apa pun yang Anda sukai
yang ini ga bisa di italic ya karena di dalam comment code

2019-03-07 15:13 UTC, wendyadi commented
@nusendra @mazipan 
Another ss yak:

<img width="621" alt="screen shot 2019-03-07 at 22 13 35" src="https://user-images.githubusercontent.com/13862336/53966711-46914900-4126-11e9-9b29-3d0c0b04165f.png">

2019-03-07 15:21 UTC, mazipan commented
Periksa ulang komentar2nya ya mas @wendyadi

2019-03-07 15:43 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +Hasil *render* dari sebuah komponen secara utama ditentukan oleh properti-properti yang diterima komponen tersebut. Jika hasil *render* dari sebuah komponen hanya bergantung pada properti-nya -- maka
props disini kan bukan properti.

2019-03-07 15:43 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +Hasil *render* dari sebuah komponen secara utama ditentukan oleh properti-properti yang diterima komponen tersebut. Jika hasil *render* dari sebuah komponen hanya bergantung pada properti-nya -- maka
props tetep pakai props

2019-03-07 15:58 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +Untuk informasi yang lebih mendalam untuk *unit testing* di Vue, kunjungi [Vue Test Utils](https://vue-test-utils.vuejs.org/) dan *cookboook entry* kami tentang [unit testing vue components](https://
cookbook entry -> buku panduan

2019-03-07 15:58 UTC, mazipan commented on src/v2/guide/unit-testing.md
> +Karena Vue [melakukan update pada DOM secara asynchronous](reactivity.html#Async-Update-Queue), *assertion* pada *update* DOM yang disebabkan oleh perubahan *state* harus dilakukan dalam callback `Vu
update -> pembaruan

2019-03-08 04:02 UTC, mazipan approved these changes

2019-03-08 04:03 UTC, merged