Halaman Introduction
vuejs-id/docs pull request #69
Opened 2019-03-07 13:14 UTC by nusendra

2019-03-07 13:39 UTC, mazipan commented on src/v2/guide/index.md
> +title: Pengantar
Gak pake "perkenalan" aja mas?

2019-03-07 13:41 UTC, mazipan requested changes

2019-03-07 13:41 UTC, mazipan commented on src/v2/guide/index.md
> +Vue (cara pengucapannya /vjuː/, seperti **view**) adalah sebuah **progressive framework** untuk membangun antarmuka pengguna. Tidak seperti beberapa framework monolitik yang lain, Vue dirancang dari
Framework diterjemahkan jadi kerangka kerja aja mas

2019-03-07 13:41 UTC, mazipan commented on src/v2/guide/index.md
> +Vue (cara pengucapannya /vjuː/, seperti **view**) adalah sebuah **progressive framework** untuk membangun antarmuka pengguna. Tidak seperti beberapa framework monolitik yang lain, Vue dirancang dari
**kerangka kerja nan progresif**

2019-03-07 13:44 UTC, mazipan requested changes

2019-03-07 13:44 UTC, mazipan commented on src/v2/guide/index.md
> +Vue (cara pengucapannya /vjuː/, seperti **view**) adalah sebuah **progressive framework** untuk membangun antarmuka pengguna. Tidak seperti beberapa framework monolitik yang lain, Vue dirancang dari
From the ground up -> dari dasar sekali

2019-03-07 13:50 UTC, mazipan commented on src/v2/guide/index.md
> +Jika anda ingin mempelajari lebih lanjut tentang Vue sebelum menyelam lebih dalam, kami <a id="modal-player"  href="#">membuat sebuah video</a> tentang prinsip - prinsip inti dan contoh proyek.
sebelum mempelajari lebih lanjut

2019-03-07 13:50 UTC, mazipan commented on src/v2/guide/index.md
> +Jika anda adalah seorang frontend developer yang berpengalaman dan ingin tahu bagaimana Vue dibandingkan dengan pustaka/framework yang lain, silakan kunjungi [Perbandingan dengan framework yang lain]
frontend developer pake italic mas

2019-03-07 13:58 UTC, nusendra commented on src/v2/guide/index.md
> +title: Pengantar
Boljug wkwk. siap

2019-03-07 14:04 UTC, nusendra commented on src/v2/guide/index.md
> +Jika anda ingin mempelajari lebih lanjut tentang Vue sebelum menyelam lebih dalam, kami <a id="modal-player"  href="#">membuat sebuah video</a> tentang prinsip - prinsip inti dan contoh proyek.
yang ini kayaknya kata sebelum menyelam lebih dalam bisa dihapus nih. Ga perlu pake itu juga masih dapet penyampaiannya

karena kalau ada double kata `mempelajari lebih lanjut`, bakalan jadi aneh

2019-03-07 14:23 UTC, mazipan requested changes

2019-03-07 14:23 UTC, mazipan commented on src/v2/guide/index.md
> +Vue (cara pengucapannya /vjuː/, seperti **view**) adalah sebuah kerangka kerja nan progresif untuk membangun antarmuka pengguna. Tidak seperti beberapa framework monolitik yang lain, Vue dirancang da
Masih ada framework

2019-03-07 14:23 UTC, mazipan commented on src/v2/guide/index.md
> +Vue (cara pengucapannya /vjuː/, seperti **view**) adalah sebuah kerangka kerja nan progresif untuk membangun antarmuka pengguna. Tidak seperti beberapa framework monolitik yang lain, Vue dirancang da
Pustaka inti nya -> Pustaka intinya

2019-03-07 14:23 UTC, mazipan commented on src/v2/guide/index.md
> +Vue (cara pengucapannya /vjuː/, seperti **view**) adalah sebuah kerangka kerja nan progresif untuk membangun antarmuka pengguna. Tidak seperti beberapa framework monolitik yang lain, Vue dirancang da
di fokuskan -> difokuskan

2019-03-07 14:23 UTC, mazipan commented on src/v2/guide/index.md
> +Jika anda adalah seorang *frontend developer* yang berpengalaman dan ingin tahu bagaimana Vue dibandingkan dengan pustaka/framework yang lain, silakan kunjungi [Perbandingan dengan framework yang lai
framework kita translate semua mas

2019-03-07 14:23 UTC, mazipan commented on src/v2/guide/index.md
> +<p class="tip">Panduan resmi ini mengasumsikan bahwa pengetahuan pembaca berada di tingkat menengah tentang HTML, CSS, dan Javascript. Jika anda benar - benar baru di pengembangan aplikasi frontend,
pembaca -> Anda

2019-03-07 14:23 UTC, mazipan commented on src/v2/guide/index.md
> +Pada halaman [Instalasi](installation.html) tersedia lebih banyak opsi ketika memulai instalasi Vue. Catatan: Kami **tidak** menyarankan para pemula untuk memulai proyek dengan menggunakan `vue-cli`,
bernama Node.js -> berbasiskan Node.js

2019-03-07 14:23 UTC, mazipan commented on src/v2/guide/index.md
> +Kita telah berhasil membuat aplikasi Vue pertama kita! Jika kita perhatikan proses *rendering* nya masih sama seperti *string template* yang biasa, tetapi Vue disini sudah membantu banyak pekerjaan k
javascript -> JavaScript

2019-03-07 14:23 UTC, mazipan commented on src/v2/guide/index.md
> +Cobalah buka console di browser Anda sekali lagi, dan ketikkan `app3.terlihat = false` kemudian tekan enter. Maka pesan yang tadi akan hilang
konsol
peramban

2019-03-08 01:18 UTC, mazipan approved these changes

2019-03-08 01:18 UTC, merged