ready review
vuejs-id/docs pull request #73
Opened 2019-03-08 14:07 UTC by Bbw0706

2019-03-08 14:08 UTC, Bbw0706 commented
@mazipan @nusendra bisa di cek mas

2019-03-08 17:18 UTC, andriawan commented on src/v2/guide/state-management.md
> +## Implementasi Seperti Flux Resmi
Saya rasa Flux like tidak perlu diterjemahkan tapi diberi penjelasan
```suggestion
## Implementasi Flux-Like (Sejenis Flux) Resmi
```

2019-03-08 17:21 UTC, Bbw0706 commented
oke sudah saya commit updatenya mas

2019-03-08 17:23 UTC, andriawan commented
selebihnya tunggu feedback mas @mazipan dan @nusendra mas @Bbw0706

2019-03-09 03:15 UTC, mazipan requested changes

2019-03-09 03:15 UTC, mazipan commented on src/v2/guide/state-management.md
> +<div class="vue-mastery"><a href="https://www.vuemastery.com/courses/mastering-vuex/intro-to-vuex/" target="_blank" rel="noopener" title="Vuex Tutorial">Lihatlah sebuah video yang menjelaskan tentang
Tonton video penjelasan di Vue Mastery

2019-03-09 03:15 UTC, mazipan commented on src/v2/guide/state-management.md
> +Jika kamu pernah menggunakan React, kamu mungkin ingin tahu perbandingan vuex dan [redux](https://github.com/reactjs/redux), Libary untuk implementasi Flux yang paling populer. Redux sebenarnya hanya
Library -> Pustaka

2019-03-09 03:15 UTC, mazipan commented on src/v2/guide/state-management.md
> +Jika kamu pernah menggunakan React, kamu mungkin ingin tahu perbandingan vuex dan [redux](https://github.com/reactjs/redux), Libary untuk implementasi Flux yang paling populer. Redux sebenarnya hanya
Redux sebenarnya tidak tergantung pada suatu lapisan tampilan

2019-03-09 03:15 UTC, mazipan commented on src/v2/guide/state-management.md
> +Jika kamu pernah menggunakan React, kamu mungkin ingin tahu perbandingan vuex dan [redux](https://github.com/reactjs/redux), Libary untuk implementasi Flux yang paling populer. Redux sebenarnya hanya
dengan cara via -> dengan cara

2019-03-09 03:15 UTC, mazipan commented on src/v2/guide/state-management.md
> +Jika kamu pernah menggunakan React, kamu mungkin ingin tahu perbandingan vuex dan [redux](https://github.com/reactjs/redux), Libary untuk implementasi Flux yang paling populer. Redux sebenarnya hanya
simple binding -> binding sederhana

2019-03-09 03:16 UTC, mazipan commented
Masih banyak kalimat yang susah dipahami maksudnya, bisa minta tolong coba dibaca ulang dari awal sampai akhir. Buat mastiin maksudnya nyampe ke pembaca

2019-03-09 03:21 UTC, mazipan requested changes

2019-03-09 03:21 UTC, mazipan commented on src/v2/guide/state-management.md
> +Saat kita melanjutkan pengembangan ketentuannya dimana component tidak boleh merubah state yang dimiliki oleh store secara langsung, tapi sebagai gantinya kita harus mengirim event untuk memberitahu
Enaknya dikasih koma.
Saat kita melanjutkan pengembangan, ada ketentuan dimana komponen....

2019-03-09 03:21 UTC, mazipan commented on src/v2/guide/state-management.md
> +Saat kita melanjutkan pengembangan ketentuannya dimana component tidak boleh merubah state yang dimiliki oleh store secara langsung, tapi sebagai gantinya kita harus mengirim event untuk memberitahu
component -> komponen
merubah -> mengubah

2019-03-09 03:21 UTC, mazipan commented on src/v2/guide/state-management.md
> +Saat kita melanjutkan pengembangan ketentuannya dimana component tidak boleh merubah state yang dimiliki oleh store secara langsung, tapi sebagai gantinya kita harus mengirim event untuk memberitahu
terimplement -> terpasang

2019-03-09 03:21 UTC, mazipan commented on src/v2/guide/state-management.md
> +Saat kita melanjutkan pengembangan ketentuannya dimana component tidak boleh merubah state yang dimiliki oleh store secara langsung, tapi sebagai gantinya kita harus mengirim event untuk memberitahu
alat debugging -> alat debug

2019-03-09 03:24 UTC, mazipan requested changes

2019-03-09 03:24 UTC, mazipan commented on src/v2/guide/state-management.md
> +## Pengelolaan State dari Awal Dengan Mudah
Pengelolaan State Sederhana dari Awal

2019-03-09 03:24 UTC, mazipan commented on src/v2/guide/state-management.md
> +Sekarang saat `Sumber Kebenaran` dirubah, kedua `vmA` dan `vmB` akan merubah tampilan mereka secara otomatis. Subcomponents dalam beberapa instance ini juga perlu mengaksesnya dengan `this.$root.$dat
sourceOfTruth gak boleh diterjemahkan disini

2019-03-09 04:20 UTC, nusendra requested changes
- Banyak kata kata / kalimat yang masih kaku (ala ala google translate) dan perlu untuk di terjemahkan secara natural indonesia
- Masih banyak versi inggris yang engga italic
- Beberapa ada typo, seperti karna => karena
- Kamu => Anda

Sudah saya beri suggestion yang benar, silakan diganti sesuai dengan itu. Thanks mas :-)

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Aplikasi besar bisa tumbuh menjadi sangat kompleks, dikarnakan banyak sekali bagian dari state yang tersebar ke components dan berinteraksi dengan mereka. Untuk mengatasi masalah ini, Vue menawarkan
```suggestion
Aplikasi besar bisa tumbuh menjadi sangat kompleks, dikarenakan banyak sekali bagian dari state yang tersebar ke seluruh komponen dan berinteraksi dengan mereka. Untuk mengatasi masalah ini, Vue menawarkan [vuex](https://github.com/vuejs/vuex): Sebuah pustaka yang berfungsi untuk mengelola state buatan kami sendiri. Ia bahkan mampu terintegrasi dengan [vue-devtools](https://github.com/vuejs/vue-devtools), dan juga kita tidak perlu mempersiapkan apa-apa (tidak perlu melakukan konfigurasi khusus) untuk bisa mengakses [time travel debugging](https://raw.githubusercontent.com/vuejs/vue-devtools/master/media/demo.gif).
```
Masih kurang natural, sudah saya perbaiki seperti diatas.

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +<div class="vue-mastery"><a href="https://www.vuemastery.com/courses/mastering-vuex/intro-to-vuex/" target="_blank" rel="noopener" title="Vuex Tutorial">Lihatlah sebuah video yang menjelaskan tentang
```suggestion
<div class="vue-mastery"><a href="https://www.vuemastery.com/courses/mastering-vuex/intro-to-vuex/" target="_blank" rel="noopener" title="Vuex Tutorial">Tonton video penjelasannya di Vue Mastery</a></div>
```

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Jika kamu pernah menggunakan React, kamu mungkin ingin tahu perbandingan vuex dan [redux](https://github.com/reactjs/redux), Libary untuk implementasi Flux yang paling populer. Redux sebenarnya hanya
```suggestion
Jika Anda pernah menggunakan React, Anda mungkin ingin tahu perbandingan antara vuex dan [redux](https://github.com/reactjs/redux), sebuah pustaka untuk implementasi Flux yang paling populer. Redux sebenarnya hanya sebatas lapisan di tampilan saja, jadi bisa digunakan bersama-sama dengan Vue secara mudah melalui [simple bindings](https://yarnpkg.com/en/packages?q=redux%20vue&p=1). Vuex berbeda karena ia terhubung dengan aplikasi Vue secara langsung. Oleh sebab itu, Vuex ini bisa lebih baik diintegrasikan dengan Vue, dan juga Vuex menawarkan API yang lebih intuitif serta meningkatkan pengalaman para pengembang.
```
Ada beberapa kata yang harus diubah agar lebih enak dibaca
seperti pengalaman pengembangan, boleh kita ubah jadi pengalaman para pengembang.

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Sering diabaikan bahwa sumber kebenaran di aplikasi Vue adalah `data` objek yang mentah - sebuah instance Vue hanya wakil untuk mengakasesnya. Karna itu, jika kamu memiliki bagian state yang ingin di
```suggestion
Hal ini seringkali diabaikan bahwa sumber kebenaran di aplikasi Vue adalah objek `data` yang mentah - hanya *instance* Vue yang boleh mengakasesnya. Oleh karena itu, jika Anda memiliki beberapa state yang ingin di bagikan ke beberapa *instance*, Anda bisa membaginya dengan identitas:
```
kamu => Anda
instance pakai italic
kurang natural

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Sekarang saat `Sumber Kebenaran` dirubah, kedua `vmA` dan `vmB` akan merubah tampilan mereka secara otomatis. Subcomponents dalam beberapa instance ini juga perlu mengaksesnya dengan `this.$root.$dat
```suggestion
Sekarang kapanpun `Sumber Kebenaran` diubah, kedua `vmA` dan `vmB` akan merubah tampilan mereka secara otomatis. Sub komponen dalam beberapa *instance* ini juga bisa mengaksesnya dengan cara `this.$root.$data`. Sekarang kita punya satu sumber kebenaran, namun ketika melakukan proses *debugging* akan terasa sangat sulit sekali. Setiap bagian dari data bisa berubah dengan setiap bagian dari aplikasi kita setiap waktunya, tanpa meninggalkan bekas sama sekali.
```
naturalisasi

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Perhatikan semua action yang merubah state dari store diletakkan didalam store itu sendiri. Tipe pengelolaan state yang terpusat ini membuat semakin mudah untuk mengerti bahwa tipe perubahan apa yang
```suggestion
Perhatikan semua *action* yang merubah *state* dari *store* diletakkan didalam *store* itu sendiri. Tipe pengelolaan state yang terpusat seperti ini semakin memudahkan kita untuk mengerti bahwa tipe perubahan apa yang bisa terjadi dan bagaimana mereka dijalankan. Sekarang saat terjadi kesalahan, kita juga bisa memiliki sebuah catatan bagaimana dan kenapa bisa terjadi *bug*.
```
naturalisasi dan italic untuk english version

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Sebagai tambahan, setiap instance/component tetap bisa memiliki dan mengelola state milik mereka sendiri:
```suggestion
Sebagai tambahan, setiap *instance*/komponen tetap bisa memiliki dan mengelola state milik mereka sendiri:
```
italic untuk inggris

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +<p class="tip">Sangat penting untuk mencatat bahwa kamu jangan pernah menggantikan state sebenarnya pada action mu - component dan store harus berbagi acuan objek yang sama supaya perubahan bisa diam
```suggestion
<p class="tip">Sebagai catatan penting, Anda jangan pernah menggantikan state asli pada *action* yang Anda buat - komponen dan *store* perlu untuk berbagi data referensi kedalam objek yang sama supaya perubahan bisa diamati.</p>
```
kamu => Anda
natural

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +<div class="vue-mastery"><a href="https://www.vuemastery.com/courses/mastering-vuex/intro-to-vuex/" target="_blank" rel="noopener" title="Vuex Tutorial">Lihatlah sebuah video yang menjelaskan tentang
```suggestion
<div class="vue-mastery"><a href="https://www.vuemastery.com/courses/mastering-vuex/intro-to-vuex/" target="_blank" rel="noopener" title="Vuex Tutorial">Tonton video penjelasannya di Vue Mastery</a></div>
```
natural

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Jika kamu pernah menggunakan React, kamu mungkin ingin tahu perbandingan vuex dan [redux](https://github.com/reactjs/redux), Libary untuk implementasi Flux yang paling populer. Redux sebenarnya hanya
```suggestion
Jika Anda pernah menggunakan React, Anda mungkin ingin tahu perbandingan antara vuex dengan [redux](https://github.com/reactjs/redux), sebuah pustaka untuk implementasi Flux yang paling populer. Redux sebenarnya hanya sebatas lapisan di tampilan saja, jadi bisa digunakan bersama - sama dengan Vue secara mudah melalui [simple bindings](https://yarnpkg.com/en/packages?q=redux%20vue&p=1). Vuex berbeda karena ia langsung terhubung dengan aplikasi Vue. Oleh karena itu, Vuex lebih cocok jika di integrasikan dengan Vue, dan juga Vuex menawarkan API yang lebih intuitif dan mampu meningkatkan pengalaman para pengembang.
```
- ada typo
- kamu => Anda
- kurang natural

pengalaman pengembangan => terdengar sangat aneh, maka kita boleh ubah menjadi
pengalaman para pengembang. Maksud berbeda, tapi tujuan yang di sampaikan sama. Jadi boleh untuk merubah maksud asalkan tujuan nya sama. Biar lebih natural dan enak dibaca

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Sering diabaikan bahwa sumber kebenaran di aplikasi Vue adalah `data` objek yang mentah - sebuah instance Vue hanya wakil untuk mengakasesnya. Karna itu, jika kamu memiliki bagian state yang ingin di
```suggestion
Hal ini sering diabaikan bahwa sumber kebenaran di aplikasi Vue adalah objek `data` yang mentah - hanya instance Vue saja yang boleh mengaksesnya. Oleh karna itu, jika Anda memiliki beberapa *state* yang ingin di bagikan ke beberapa instance yang lain, Anda bisa membaginya dengan identitas:
```
kurang natural dan ada typo

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Sekarang saat `Sumber Kebenaran` dirubah, kedua `vmA` dan `vmB` akan merubah tampilan mereka secara otomatis. Subcomponents dalam beberapa instance ini juga perlu mengaksesnya dengan `this.$root.$dat
```suggestion
Sekarang, kapanpun `Sumber Kebenaran` diubah, kedua `vmA` dan `vmB` akan merubah tampilan mereka secara otomatis. Sub komponen yang ada di dalam beberapa *instance* ini juga bisa mengaksesnya dengan cara `this.$root.$data`. Sekarang kita sudah punya satu sumber kebenaran, namun untuk melakukan proses *debugging* akan terasa sangat sulit sekali. Setiap bagian dari data bisa berubah dikarenakan perubahan dari setiap bagian dari aplikasi kita, setiap waktunya, tanpa meninggalkan bekas sama sekali.
```
kurang natural

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Perhatikan semua action yang merubah state dari store diletakkan didalam store itu sendiri. Tipe pengelolaan state yang terpusat ini membuat semakin mudah untuk mengerti bahwa tipe perubahan apa yang
```suggestion
Perhatikan semua *action* yang merubah *state* diletakkan didalam store itu sendiri. Tipe pengelolaan state yang terpusat ini memudahkan kita untuk mengerti, tipe perubahan apa yang bisa terjadi dan bagaimana mereka dijalankan. Sekarang saat terjadi sebuah kesalahan, kita juga bisa memiliki sebuah catatan kenapa hal itu bisa menyebabkan munculnya *bug*.
```
inggris perlu italic, dan masih kurang natural

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Sebagai tambahan, setiap instance/component tetap bisa memiliki dan mengelola state milik mereka sendiri:
```suggestion
Sebagai tambahan, setiap *instance*/komponen tetap bisa memiliki dan mengelola state milik mereka sendiri:
```

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +<p class="tip">Sangat penting untuk mencatat bahwa kamu jangan pernah menggantikan state sebenarnya pada action mu - component dan store harus berbagi acuan objek yang sama supaya perubahan bisa diam
```suggestion
<p class="tip">Sebagai catatan penting, jangan pernah mengganti *state* asli pada *actions* Anda - komponen dan *store* perlu untuk membagikan data referensi ke dalam objek yang sama supaya perubahan yang terjadi bisa diamati.</p>
```

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Saat kita melanjutkan pengembangan ketentuannya dimana component tidak boleh merubah state yang dimiliki oleh store secara langsung, tapi sebagai gantinya kita harus mengirim event untuk memberitahu
```suggestion
Saat kita melanjutkan pengembangan, ketentuannya adalah komponen tidak boleh merubah *state* yang ada di dalam store secara langsung, tetapi kita harus mengirim sebuah *event* untuk memberitahu store bahwa dia harus menjalankan sebuah *action*, yang pada akhirnya kita akan merasakan proses seperti ini sama dengan dengan arsitektur milik [Flux](https://facebook.github.io/flux/). Keuntungan menggunakan aturan ini adalah kita bisa merekam semua perubahan *state* yang terjadi pada *store* dan bisa mengimplementasikan proses *debugging helpers* seperti catatan perubahan, *snapshot*, dan bisa melihat perubahan data secara historis/*time travel*.
```
Banyak yang perlu di natural kan

2019-03-09 04:20 UTC, nusendra commented on src/v2/guide/state-management.md
> +Ini membawa kita kembali ke [vuex](https://github.com/vuejs/vuex), jadi jika kamu telah membacanya sejauh ini mungkin saatnya mencobanya!
```suggestion
Mari kembali lagi ke [vuex](https://github.com/vuejs/vuex), jadi jika Anda telah membaca panduan pengelolaan *state* sampai sejauh ini, mungkin sekarang saatnya mencoba!
```
natural

2019-03-09 05:41 UTC, nusendra requested changes
Ada beberapa yang perlu diubah. Dikit lagi mas

2019-03-09 05:41 UTC, nusendra commented on src/v2/guide/state-management.md
> +Hal ini seringkali diabaikan bahwa sumber kebenaran di aplikasi Vue adalah objek `data` yang mentah - hanya **instance** Vue yang boleh mengakasesnya. Oleh karena itu, jika Anda memiliki beberapa sta
instance pakai single *, bukan double **
kalau double ** jadi nya bold, bukan italic

mengakasesnya => mengaksesnya

2019-03-09 05:41 UTC, nusendra commented on src/v2/guide/state-management.md
> +Perhatikan semua *action* yang mengubah *state* dari store diletakkan didalam store itu sendiri. Tipe pengelolaan state yang terpusat ini membuatnya semakin mudah untuk dimengerti bahwa tipe perubaha
store harus italic

2019-03-09 05:41 UTC, nusendra commented on src/v2/guide/state-management.md
> +Jika anda pernah menggunakan React, anda mungkin ingin tahu perbandingan vuex dan [redux](https://github.com/reactjs/redux), Pustaka untuk implementasi Flux yang paling populer. Redux sebenarnya tida
```suggestion
Jika Anda pernah menggunakan React, Anda mungkin ingin tahu perbandingan antara vuex dengan [redux](https://github.com/reactjs/redux), sebuah pustaka untuk implementasi Flux yang paling populer. Redux sebenarnya hanya sebatas lapisan di tampilan saja, jadi bisa digunakan bersama - sama dengan Vue secara mudah melalui [simple bindings](https://yarnpkg.com/en/packages?q=redux%20vue&p=1). Vuex berbeda karena ia langsung terhubung dengan aplikasi Vue. Oleh karena itu, Vuex lebih cocok jika di integrasikan dengan Vue, dan juga Vuex menawarkan API yang lebih intuitif dan mampu meningkatkan pengalaman para pengembang.
```

2019-03-09 05:46 UTC, Bbw0706 commented
oke sudah di push mas @nusendra

2019-03-09 05:52 UTC, nusendra approved these changes

2019-03-09 05:52 UTC, nusendra commented
aku udah sip mas @Bbw0706 . Nunggu review nya mas @mazipan

2019-03-09 08:29 UTC, merged