PR: Halaman Plugin
vuejs-id/docs pull request #74
Opened 2019-03-09 05:26 UTC by isatrio

2019-03-09 05:50 UTC, nusendra requested changes
Dikit lagi mantul

BTW versi hexo nya diturunin mas?

2019-03-09 05:50 UTC, nusendra commented on src/v2/guide/plugins.md
> +Anda dapat secara opsional mengoper beberapa opsi:
Anda bisa secara opsional mengoper beberapa opsi
Atau
Secara opsional, Anda bisa mengoper beberapa opsi

Kalau pake kata dapat, rasanya lebih cocok diganti jadi "bisa"

2019-03-09 05:50 UTC, nusendra commented on src/v2/guide/plugins.md
> +Beberapa plugin disediakan oleh plugin Vue.js resmi seperti `vue-router` secara otomatis memanggil `Vue.use()` jika `Vue` tersedia sebagai variabel global. Bagaimanapun dalam linkungan modul seperti
explisit => eksplisit  ?

2019-03-09 05:50 UTC, nusendra commented on src/v2/guide/plugins.md
> +// Jangan lupa untuk memanggil ini
```suggestion
// Jangan lupa untuk memanggil fungsi ini
```

2019-03-09 13:18 UTC, isatrio commented on src/v2/guide/plugins.md
> +Beberapa plugin disediakan oleh plugin Vue.js resmi seperti `vue-router` secara otomatis memanggil `Vue.use()` jika `Vue` tersedia sebagai variabel global. Bagaimanapun dalam linkungan modul seperti
Sepertinya agak ngantuk tadi :D

2019-03-09 13:34 UTC, isatrio commented
Updated mas, maaf ada yang missed tadi dan versi Hexo entah kenapa kok jadi downgrade tapi udah dibenerin

2019-03-10 08:42 UTC, nusendra approved these changes

2019-03-10 08:42 UTC, merged