Menterjemahkan Kelas and Binding Gaya
vuejs-id/docs pull request #76
Opened 2019-03-10 11:06 UTC by gustialfian

Draft pertama menterjemahkan

2019-03-12 02:10 UTC, isatrio commented
@gustialfian Sedikit komentar aja soal judulnya. Penulisan yang benar adalah "Menerjemahkan" bukan "Menterjemahkan".

2019-03-12 06:03 UTC, mazipan requested changes

2019-03-12 06:03 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +Sintaksis di atas berarti kehadiran `active` akan ditentukan oleh nilai [benar](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) dari properti data `isActive`.
truthiness -> kebenaran.

2019-03-12 06:03 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +Anda dapat memiliki beberapa kelas beralih dengan memiliki banyak *field* dalam objek. Selain itu, direktif `v-bind:class` dapat berdampingan dengan atribut `class` biasa. Jadilah templat berikut:
```suggestion
Anda dapat memiliki beberapa kelas yang akan saling menggantikan dengan menambahkan lebih banyak *field* dalam objek. Selain itu, direktif `v-bind:class` dapat berdampingan dengan atribut `class` biasa. Seperti pada templat berikut:
```

2019-03-12 06:03 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +Ini akan memberikan:
```suggestion
Akan menghasilkan:
```

2019-03-12 06:03 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +Saat `isActive` atau `hasError` berubah, daftar kelas akan diperbaharui. Sebagai contoh, jika `hasError` menjadi `true`, daftar kelas akan menjadi `"static active text-danger "`.
diperbarui bukan diperbaharui

2019-03-12 06:03 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +Yang akan memberikan:
```suggestion
Yang akan menghasilkan:
```

2019-03-12 06:03 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +Ini akan selalu berlaku `errorClass`, tetapi hanya akan menerapkan `activeClass` ketika `isActive` bernilai benar.
```suggestion
Ini akan selalu menerapkan `errorClass`, dan hanya akan menerapkan `activeClass` ketika `isActive` bernilai benar.
```

2019-03-12 06:03 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +### Dengan Komponen-Komponen
Gak perlu pake kata jamak, cukup komponen. sudah mewakili maksudnya.

2019-03-12 06:53 UTC, gustialfian commented
Terimakasih reviewnya @mazipan ini Sudah saya update di [2537a6ba1e51683d804edbf11f4319a69ad43906]

2019-03-12 09:54 UTC, mazipan requested changes

2019-03-12 09:54 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +Kita dapat melempar sebuah objek ke `v-bind:class` untuk mengubah `class` secara dinamis
Kata `pass` sesuai dengan kesepakatan kita [disini](https://github.com/vuejs-id/docs/blob/master/GLOSARIUM.md), akan diterjemahkan sebagai "oper"

2019-03-12 09:54 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +Kita dapat melempar sebuah array ke `v-bind:class` untuk menerapkan daftar kelas:
Kata `pass` sesuai dengan kesepakatan kita [disini](https://github.com/vuejs-id/docs/blob/master/GLOSARIUM.md), akan diterjemahkan sebagai "oper"

2019-03-12 09:54 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +### Prefiks Otomatis
Boleh ditambahkan 
--> (*autoprefix*) 
di belakangnya gak mas?

2019-03-12 09:55 UTC, mazipan commented
Sudah bagus, setelah dibenerin komentar terakhir sudah siap di merge sepertinya ya mas @nusendra

2019-03-12 10:08 UTC, gustialfian commented
sudah saya update lagi mas di [1fe8e1933425e8e9ac4aa872dce52a65c8b924fa], untuk Prefiks Otomatis saya tambahkan dibelakangnya (Auto-prefixing)

2019-03-12 12:39 UTC, mazipan requested changes

2019-03-12 12:39 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +Kita dapat oper sebuah objek ke `v-bind:class` untuk mengubah `class` secara dinamis
mengoper mas.

2019-03-12 12:39 UTC, mazipan commented on src/v2/guide/class-and-style.md
> +Kita dapat oper sebuah array ke `v-bind:class` untuk menerapkan daftar kelas:
mengoper mas.

2019-03-13 02:00 UTC, gustialfian commented
sudah saya update mas @mazipan [9295bb252d9cbf2a7fc4115d2964e42d11db077d].

2019-03-13 05:25 UTC, mazipan approved these changes

2019-03-13 05:26 UTC, mazipan commented
Terima kasih mas @gustialfian atas kontribusinya, ditunggu PR lainnya :-D

2019-03-13 05:26 UTC, merged