menerjemahkan halaman komponen dasar
vuejs-id/docs pull request #77
Opened 2019-03-10 12:56 UTC by iamyuu

maaf terlalu lama, tolong di koreksi @mazipan

2019-03-12 06:08 UTC, mazipan requested changes

2019-03-12 06:08 UTC, mazipan commented on src/v2/guide/components.md
> +Komponen adalah Vue _instance_ yang dapat digunakan kembali dengan nama: pada kasus ini, `<button-counter>`. Kita bisa menggunakan komponen ini sebagai kustom elemen di dalam _instance_ root Vue yang
kebalik. 
diterangkan menerangkan.
elemen kustom.

2019-03-12 06:08 UTC, mazipan commented on src/v2/guide/components.md
> +Untuk menggunakan komponen ini dalam templat, mereka harus didaftarkan jadi Vue tahu tentang mereka. Ada dua tipe untuk mendaftarkan: **global** dan **local**. Sejauh ini, Kita hanya mendaftarkan kom
```suggestion
Untuk menggunakan komponen ini dalam templat, mereka harus didaftarkan agar Vue tahu tentang mereka. Ada dua tipe untuk mendaftarkan: **global** dan **lokal**. Sejauh ini, Kita hanya mendaftarkan komponen secara global, menggunakan `Vue.component`:
```

2019-03-12 07:48 UTC, iamyuu commented on src/v2/guide/components.md
> +Komponen adalah Vue _instance_ yang dapat digunakan kembali dengan nama: pada kasus ini, `<button-counter>`. Kita bisa menggunakan komponen ini sebagai kustom elemen di dalam _instance_ root Vue yang
"diterangkan menerangkan", ini bagian mana ya mas @mazipan? Ko aku cari ga ketemu

2019-03-12 09:48 UTC, mazipan commented on src/v2/guide/components.md
> +Komponen adalah Vue _instance_ yang dapat digunakan kembali dengan nama: pada kasus ini, `<button-counter>`. Kita bisa menggunakan komponen ini sebagai kustom elemen di dalam _instance_ root Vue yang
maksudnya kalau bahasa indonesia itu kata bendanya ada di paling depan, kata sifatnya ada setelahnya.

jadi kalau ada kata "custom element" ini di bahasa indonesia "elemen kustom"

Reading reference: https://rubrikbahasa.wordpress.com/2003/09/01/hukum-dm-dalam-bahasa-indonesia/

2019-03-12 10:42 UTC, iamyuu commented on src/v2/guide/components.md
> +Komponen adalah Vue _instance_ yang dapat digunakan kembali dengan nama: pada kasus ini, `<button-counter>`. Kita bisa menggunakan komponen ini sebagai kustom elemen di dalam _instance_ root Vue yang
Oh contoh ku kira ada yang salah, makasih mas

2019-03-12 10:42 UTC, iamyuu commented
udah aku perbarui di [5d23b61](https://github.com/vuejs-id/docs/commit/362b4713234cee0efe5e1fac992d275766cbef6d)

2019-03-19 01:41 UTC, mazipan approved these changes

2019-03-19 01:41 UTC, merged