Translation for migrating vue page
vuejs-id/docs pull request #78
Opened 2019-03-11 06:29 UTC by wendyadi

Mohon feedbacknya 🙏

2019-03-12 06:14 UTC, mazipan requested changes

2019-03-12 06:14 UTC, mazipan commented on src/v2/guide/migration-vuex.md
> +title: Migrasi dari Vuex 0.6.X ke 1.0
```suggestion
title: Migrasi dari Vuex 0.6.x ke 1.0
```

2019-03-12 06:14 UTC, mazipan commented on src/v2/guide/migration-vuex.md
> +  <h4>Jalan *Upgrade*</h4>
Path lebih cocok jadi Jalur dibandingkan Jalan

2019-03-12 06:14 UTC, mazipan commented on src/v2/guide/migration-vuex.md
> +## Store Emiter Even <sup>dihapus</sup>
```suggestion
## Emiter Event Store <sup>dihapus</sup>
```

2019-03-12 06:14 UTC, mazipan commented on src/v2/guide/migration-vuex.md
> +Instan dari store tidak lagi mengekspos interface "event emitter" (`on`, `off`, `emit`). Jika Anda menggunakan store sebagai *global event bus*, [lihat bagian ini](migration.html#dispatch-and-broadca
```suggestion
*Instance* dari store tidak lagi mengekspos interface "event emitter" (`on`, `off`, `emit`). Jika Anda menggunakan store sebagai *global event bus*, [lihat bagian ini](migration.html#dispatch-and-broadcast-removed)  untuk instruksi migrasi.
```

2019-03-15 05:19 UTC, wendyadi commented
Changed @mazipan

2019-03-15 07:14 UTC, mazipan approved these changes

2019-03-15 07:14 UTC, merged