Terjemahan Halaman Single File Component
vuejs-id/docs pull request #81
Opened 2019-03-13 09:17 UTC by adenvt

Terjemahan Halaman Single File Component ( #30 )

2019-03-14 04:04 UTC, mazipan requested changes

2019-03-14 04:04 UTC, mazipan commented on src/v2/guide/single-file-components.md
> +title: Berkas Komponen Tunggal
Komponen Berkas Tunggal

2019-03-14 04:04 UTC, mazipan commented on src/v2/guide/single-file-components.md
> +Dikebanyakan projek Vue, Komponen global akan didefinisikan menggunakan `Vue.component`, diikuti dengan `new Vue({ el: '#container' })` untuk mengarahkan ke elemen kontainer dalam *body* setiap halam
Pada kebanyakan proyek Vue

2019-03-14 04:04 UTC, mazipan commented on src/v2/guide/single-file-components.md
> +Dikebanyakan projek Vue, Komponen global akan didefinisikan menggunakan `Vue.component`, diikuti dengan `new Vue({ el: '#container' })` untuk mengarahkan ke elemen kontainer dalam *body* setiap halam
Setelah koma tidak perlu capital

2019-03-14 14:35 UTC, adenvt commented on src/v2/guide/single-file-components.md
> +Dikebanyakan projek Vue, Komponen global akan didefinisikan menggunakan `Vue.component`, diikuti dengan `new Vue({ el: '#container' })` untuk mengarahkan ke elemen kontainer dalam *body* setiap halam
fix on 50210f4

2019-03-14 14:35 UTC, adenvt commented on src/v2/guide/single-file-components.md
> +title: Berkas Komponen Tunggal
Fix on 50210f4

2019-03-15 07:11 UTC, mazipan approved these changes

2019-03-15 07:11 UTC, merged