Halaman Reactivity in Depth
vuejs-id/docs pull request #90
Opened 2019-03-18 07:35 UTC by gustialfian

Ada Beberapa kata yang saya kebingungan untuk menerjemahkannya jadi tidak saya terjemahkan:
- state
- dependency
- getter/setters
- root
- asynchronous
- event loop
- buffered
- tick
- promise

tolong direview dulu @mazipan

2019-03-18 08:24 UTC, mazipan requested changes

2019-03-18 08:24 UTC, mazipan commented on src/v2/guide/reactivity.md
> +      console.log(this.$el.textContent) // => 'diperbaharui'
diperbaharui -> diperbarui

2019-03-18 08:24 UTC, mazipan commented on src/v2/guide/reactivity.md
> +Sakarang waktunya untuk pemahaman secara mendalam! Salah satu fitur pembeda Vue adalah sistem reaktivitas yang tidak menyulitkan. Model hanyalah objek JavaScript biasa. Saat Anda memodifikasinya, tam
```suggestion
Sakarang waktunya untuk pemahaman secara mendalam! Salah satu fitur pembeda Vue adalah sistem reaktivitas yang tidak menyulitkan. Model hanyalah objek JavaScript biasa. Saat Anda memodifikasinya, tampilan diperbarui. Itu membuat manajemen *state* menjadi sederhana dan intuitif, tetapi juga penting untuk memahami cara kerjanya untuk menghindari beberapa kesalahan umum. Pada bagian ini, kita akan menggali beberapa detail sistem reaktivitas Vue pada tingkat yang lebih rendah.
```

2019-03-18 08:24 UTC, mazipan commented on src/v2/guide/reactivity.md
> +<div class="vue-mastery"><a href="https://www.vuemastery.com/courses/advanced-components/build-a-reactivity-system" target="_blank" rel="noopener" title="Vue Reactivity">Tonton penjelasan video tenta
```suggestion
<div class="vue-mastery"><a href="https://www.vuemastery.com/courses/advanced-components/build-a-reactivity-system" target="_blank" rel="noopener" title="Vue Reactivity">Tonton video penjelasan tentang Vue Mastery</a></div>
```

2019-03-18 08:24 UTC, mazipan commented on src/v2/guide/reactivity.md
> +*Getter/setters* tidak terlihat oleh pengguna, tapi memungkinkan Vue untuk melakukan pelacakan-*dependency* dan pemberitahuan-perubahan saat properti diakses atau diubah. Satu kekurangannya adalah ba
```suggestion
*Getter/setters* tidak terlihat oleh pengguna, tapi memungkinkan Vue untuk melakukan pelacakan *dependency* dan pemberitahuan perubahan saat properti diakses atau diubah. Satu kekurangannya adalah bahwa format *getter/setters* konsol peramban berbeda ketika objek data yang dikonversi dicatat, jadi Anda mungkin ingin memasang [*vue-devtools*](https://github.com/vuejs/vue-devtools) untuk antarmuka yang lebih ramah inspeksi.
```

2019-03-18 09:28 UTC, gustialfian commented
sudah direvisi mas @mazipan

2019-03-19 01:48 UTC, nusendra commented
Sudah oke nih kalo aku liat

2019-03-19 04:36 UTC, merged