Slots
vuejs-id/docs pull request #94
Opened 2019-03-20 06:58 UTC by logustra

Slots Bahasa Indonesia 😄 🚀

2019-03-20 07:48 UTC, mazipan requested changes

2019-03-20 07:48 UTC, mazipan commented on src/v2/guide/components-slots.md
> +> Sebelum lanjut membaca halaman ini, kami berasumsi bahwa Anda telah membaca [Dasar-Dasar Komponen](components.html). Baca halaman itu terlebih dahulu bila Anda belum mengerti tentang komponen.
Samain sama yang di: https://docs.vuejs.id/v2/guide/components-props.html

2019-03-20 09:30 UTC, logustra commented on src/v2/guide/components-slots.md
> +> Sebelum lanjut membaca halaman ini, kami berasumsi bahwa Anda telah membaca [Dasar-Dasar Komponen](components.html). Baca halaman itu terlebih dahulu bila Anda belum mengerti tentang komponen.
kemarin yang https://github.com/vuejs-id/docs/pull/75 saya samakan seperti https://docs.vuejs.id/v2/guide/components-props.html, cuma kemarin ada masukan dari mas @nusendra , dan menurut saya ini lebih natural daripada yang ini https://docs.vuejs.id/v2/guide/components-props.html mas @mazipan

2019-03-20 09:31 UTC, logustra commented on src/v2/guide/components-slots.md
> +> Sebelum lanjut membaca halaman ini, kami berasumsi bahwa Anda telah membaca [Dasar-Dasar Komponen](components.html). Baca halaman itu terlebih dahulu bila Anda belum mengerti tentang komponen.
menurut mas @mazipan  gimana?

2019-03-20 12:03 UTC, nusendra commented on src/v2/guide/components-slots.md
> +> Sebelum lanjut membaca halaman ini, kami berasumsi bahwa Anda telah membaca [Dasar-Dasar Komponen](components.html). Baca halaman itu terlebih dahulu bila Anda belum mengerti tentang komponen.
saya sih oke pakai yang ini @logustra

2019-03-22 14:11 UTC, mazipan commented
Bantu review ini juga ya mas @nusendra

2019-03-23 05:08 UTC, nusendra commented
oke mas @mazipan

2019-03-25 14:38 UTC, isatrio commented
Kebanyakan, kesalahan ada di kata "di" yang seharusnya dipisah karena menunjukan tempat. Mungkin perlu diperiksa kembali.

2019-03-25 14:39 UTC, isatrio reviewed
Beberapa yang masih perlu dibenahi

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +> Sebelum lanjut membaca halaman ini, kami berasumsi bahwa Anda telah membaca [Dasar-Dasar Komponen](components.html). Baca halaman itu terlebih dahulu bila Anda belum mengerti tentang komponen.
Saya kurang sreg dengan kalimat ini, "Sebelum lanjut membaca halaman ini" 
Bisa diubah seperti ini kah? "Sebelum mulai membaca halaman ini"

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +Saat Anda ingin menggunakan data didalam *slot*, seperti ini:
"di" menunjukkan tempat seharusnya dipisah. Bedakan "di" imbuhan dan "di" menunjukan tempat.

Contoh:
Diganti - Diubah - Diterjang
Di sana - Di dalam - Di mana

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +  Klik disini dan Anda akan diarahkan ke: {{ url }}
"di" dalam "disini" seharusnya dipisah

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +> Semua yang ada di templat induk, akan dikompilasi didalam *scope* induk; semua yang ada di templat anak, akan dikompilasi didalam *scope* anak.
"di dalam"

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +Ada beberapa kasus yang bermanfaat untuk menentukan konten *slot fallback* (*slot default*), yang hanya akan di-*render* ketika konten slot telah kita sediakan. Misalnya, didalam komponen `<submit-bu
Untuk kalimat di bawah sepertinya ada yang terlupa ada kata "no"

"to be rendered only when no content is provided."

Mungkin bisa jadi seperti di bawah

"yang hanya akan di-render ketika tidak ada konte yang tersedia".

Kata "didalam" seharusnya "di dalam".

Untuk "for example" lebih baik "sebagai contoh" atau "misalnya" mas @mazipan , mas @nusendra ?

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +Sekarang saat kita menggunakan `<submit-button>` sebagai komponen induk, yang tidak kita sediakan konten didalamnya:
"in" seharusnya diartikan "dalam"

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +    <!-- Kita ingin konten *header* disini -->
@nusendra @mazipan 

Untuk "header", "main", dan "footer" apakah tidak sebaiknya diartikan saja dalam konteks ini?

header = tajuk/kepala
main = utama
footer = tampilan bawah/kaki

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +Untuk membuat data `user` tersedia di induk konten *slot*, kita bisa *bind* data `user` sebagai attribut di elemen `<slot>`:
typo "attribut"

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +Namun, ini bahkan nyaris tidak menjelaskan apa saja yang bisa *slot* lakukan. Di dunia nyata, contoh yang bagus untuk penggunaan *slot*, kami sarankan untuk menelusuri perpustakaan seperti [Vue Virtu
"libraries" mungkin lebih baik diartikan menjadi "pustaka" saja.

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +Sekarang saat kita menggunakan komponen `<todo-list>`, secara opsional kita bisa mendifinisikan alternatif `<template>` untuk item *todo*, tapi dengan akses ke data dari anak:
item = butir

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +    Kita mimiliki *slot* untuk setiap `todo`, kemudian oper `todo` object sebagai *props*.
"kemudian oper objek `todo`sebagai properti/*prop* slot" ?

2019-03-25 14:39 UTC, isatrio commented on src/v2/guide/components-slots.md
> +***Slot props* memungkinkan kita untuk merubah *slot* menjadi templat yang dapat digunakan kembali, dan bisa di-*render* dengan konten yang berbeda, yang berbasis pada input *props*.** Ini sangat ber
kata imbuhan yang benar untuk "ubah" adalah "mengubah" bukan "merubah"

2019-03-25 17:06 UTC, mandaputtra reviewed
small review and comment, pada slot

2019-03-25 17:06 UTC, mandaputtra commented on src/v2/guide/components-slots.md
> +Konten tersebut akan di-*render* sebagai gantinya:
tidak perlu ditambahkan **gantinya** atau tambahkan kata **gantinya** di depan kalimat

Jika diurut dari 1 kata di atas, bisa ini :

```
Akan tetapi jika kita menyediakan konten di komponen tersebut =>  konten tersebut akan di-*render* sebagai
```

atau

```
Akan tetapi jika kita menyediakan konten di komponen tersebut =>  gantinya konten tersebut akan di-*render* sebagai
```

2019-03-25 17:06 UTC, mandaputtra commented on src/v2/guide/components-slots.md
> +    <!-- Kita ingin konten *header* disini -->
Menurut saya boleh dibiarkan seperti itu mas, nanti ditambahkan pada glosarium. Kata ini terlalu mainstream di web development baiknya untuk menggunakan kata tersebut.

2019-03-25 17:06 UTC, mandaputtra commented on src/v2/guide/components-slots.md
> +HTML yang kita tempatkan di antara templat `<template>` akan di-*render* seperti ini:
`Either way` harap diartikan. 

masukan, diambil dari satu kata diatas-nya.
```
Namun ... jika Anda ingin lebih eksplisit => Jika tidak, HTML yang kita tempatkan di antara templat `<template>` akan di-*render* seperti ini
```

2019-03-25 17:06 UTC, mandaputtra commented on src/v2/guide/components-slots.md
> +## Slot yang Memiliki Nama
@nusendra @mazipan 

Apakah semua judul section diartikan seperti ini mas? akan lebih baik jika ini diartikan ke bahasa Indonesia kita menyematkan kata asli Inggrisnya, ini akan lebih membantu banyak pemula saat dia sedang kebingungan ada masalah dengan `Named Slot`, di Om StackOverflow dan Mbah Google, setidaknya seperti itu. Mengingat sumber *error-solving* kebanyakan berasal dari bahasa Inggris.

Saran saya :

```md
# Slot yang memiliki nama (Named Slot)
```

2019-03-25 22:54 UTC, mazipan commented on src/v2/guide/components-slots.md
> +## Slot yang Memiliki Nama
Setuju, untuk kata yang sulit dipahami pada awal penggunaan di suatu halaman baiknya memang ditambahkan kaya aslinya. Untuk penggunaan selanjutnya tidak perlu, agar pembaca tau konteks yang dimaksud

2019-03-25 22:56 UTC, mazipan commented on src/v2/guide/components-slots.md
> +    <!-- Kita ingin konten *header* disini -->
header yang dimaksud disini kan tag `header`. Jadi lebih baik dipertahankan saja biar ketahuan korelasinya.

2019-03-26 04:13 UTC, logustra commented on src/v2/guide/components-slots.md
> +Sekarang saat kita menggunakan komponen `<todo-list>`, secara opsional kita bisa mendifinisikan alternatif `<template>` untuk item *todo*, tapi dengan akses ke data dari anak:
saya rasa item tidak perlu di artikan mas @isatrio karena akan terdengar aneh

2019-03-26 05:00 UTC, logustra commented
Thanks masukannya mas @isatrio @mandaputtra

2019-03-27 11:28 UTC, mazipan commented
Kalau sudah okey bantu approve ya mas @mandaputtra atau @isatrio, biar ketahuan udah di review.

2019-03-27 12:08 UTC, mandaputtra commented
Okay thanks a lot mas @logustra, sudah saya baca lagi sekali 👍 💯 LGTM. 

Saya rasa sudah oke untuk di merge mas @mazipan. apakah review mas sudah oke?

2019-03-27 12:12 UTC, mazipan commented
Aman mas @mandaputtra

2019-03-27 12:12 UTC, mazipan approved these changes

2019-03-27 12:12 UTC, merged