[WIP] Feature/installasi bahasa indonesia
vuejs-id/docs pull request #99
Opened 2019-03-28 09:17 UTC by adenvt

Maaf, belum bisa menyelesaikan, masih ada kesibukan lain. :pray: :pray: :pray:

2019-03-28 09:45 UTC, nusendra requested changes
Mayoritas udah bagus dan natural. Cuma ada beberapa yang perlu ditambahkan agar lebih mudah dipahami

2019-03-28 09:45 UTC, nusendra commented on src/v2/guide/installation.md
> +Ketika menggunakan Vue, kami menyarankan untuk menginstal juga [Vue Devtools](https://github.com/vuejs/vue-devtools#vue-devtools) di peramban Anda, memungkinkan Anda untuk menginspeksi dan *debug* ap
```suggestion
Ketika menggunakan Vue, kami menyarankan untuk menginstal [Vue Devtools](https://github.com/vuejs/vue-devtools#vue-devtools) juga di peramban Anda, yang memungkinkan Anda untuk menginspeksi dan *debug* aplikasi Vue Anda dengan antarmuka yang lebih *user-friendly*.
```
naturalisasi

2019-03-28 09:45 UTC, nusendra commented on src/v2/guide/installation.md
> +Anda dapat menjelajahi *source* dari paket NPM di [cdn.jsdelivr.net/npm/vue](https://cdn.jsdelivr.net/npm/vue/).
dapat => bisa

lebih natural pakai kata bisa

2019-03-28 09:45 UTC, nusendra commented on src/v2/guide/installation.md
> +Vue juga tersedia di [unpkg](https://unpkg.com/vue@{{vue_version}}/dist/vue.js) dan [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/vue/{{vue_version}}/vue.js) (cdnjs membutuhkan waktu untuk singkroni
```suggestion
Vue juga tersedia di [unpkg](https://unpkg.com/vue@{{vue_version}}/dist/vue.js) dan [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/vue/{{vue_version}}/vue.js) (cdnjs membutuhkan waktu untuk singkronisasi, sehingga rilis yang terbaru mungkin belum tersedia).
```
`rilis mungkin terakhir belum tersedia` Kata kata ini membingungkan.

2019-03-28 09:45 UTC, nusendra commented on src/v2/guide/installation.md
> +Pastikan untuk membaca tentang [perbedaan _build_ Vue](#Explanation-of-Different-Builds) dan gunakan **versi produksi** dalam situs yang Anda *publish*, mengganti `vue.js` dengan `vue.min.js`. Build
```suggestion
Pastikan untuk membaca tentang [perbedaan _build_ Vue](#Explanation-of-Different-Builds) dan gunakan **versi produksi** dalam situs yang Anda *publish*, dengan cara mengganti `vue.js` dengan `vue.min.js`. Build ini lebih kecil dan dioptimasi untuk kecepatan dari pada pengalaman pengembangan (*development experience*).
```
natural

2019-03-28 09:45 UTC, nusendra commented on src/v2/guide/installation.md
> +<p class="tip">CLI mengasumsikan pengetahuan tentang Node.js sebelumnya dan <i>build tool</i> yang terkait. Jika Anda baru dalam Vue atau <i>build tool</i> <i>front-end</i>, kami sangat menyarankan m
```suggestion
<p class="tip">CLI mengasumsikan pengetahuan tentang Node.js sebelumnya dan <i>build tool</i> yang terkait. Jika Anda baru mempelajari Vue atau <i>build tool</i> <i>front-end</i>, kami sangat menyarankan Anda untuk mengikuti <a href="./">petunjuk</a> tanpa <i>build tool</i> apapun sebelum menggunakan CLI.</p>
```
naturalisasi

2019-03-28 09:45 UTC, nusendra commented on src/v2/guide/installation.md
>  - **[CommonJS](http://wiki.commonjs.org/wiki/Modules/1.1)**: CommonJS builds are intended for use with older bundlers like [browserify](http://browserify.org/) or [webpack 1](https://webpack.github.i
ini belum ya mas

2019-03-28 15:29 UTC, mandaputtra commented
Ga masalah mas mas @adenvt LGTM

2019-04-15 07:36 UTC, mazipan commented
ini gimana @adenvt @mandaputtra @nusendra ?

2019-04-15 14:19 UTC, adenvt commented
Mohon maaf, ini di takeover aj. Saya lagi ada kesibukan yang tidak bisa ditinggal, mohon maaf banget :pray: :pray:

2019-04-15 16:15 UTC, closed without merging